In [1]:
import time
import numpy as np
import matplotlib
from matplotlib import pyplot as plt
from pandas.plotting import scatter_matrix
import os
import re
import pandas as pd
import numpy as np
from IPython.display import Audio
import seaborn as sns

import helpers # this is where the main training/decoding functions are, modified from teh original HIVAE main.py

#import warnings 
#warnings.filterwarnings('ignore') ########## NOTE: comment out for testing in case it's hiding problems

def set_settings(opts,nepochs=500,modload=False,save=True): # note: modload doesnt do anything right now, hardcoded in helpers.py
    'replace setting template placeholders with file info'
    inputf=re.sub('.csv','',opts['files'].iloc[0])
    missf=inputf+'_missing.csv'
    typef=inputf+'_types.csv'
    
    template = '--epochs NEPOCHS --model_name model_HIVAE_inputDropout --restore MODLOAD \
        --data_file data_python/INPUT_FILE.csv --types_file data_python/TYPES_FILE \
         --batch_size NBATCH --save NEPFILL --save_file SAVE_FILE\
        --dim_latent_s SDIM --dim_latent_z 1 --dim_latent_y YDIM \
         --miss_percentage_train 0 --miss_percentage_test 0 \
        --true_miss_file data_python/MISS_FILE --learning_rate LRATE'
    
    # replace placeholders in template
    settings = re.sub('INPUT_FILE',inputf,template)
    settings = re.sub('NBATCH',str(opts['nbatch'].iloc[0]),settings)
    settings = re.sub('NEPOCHS',str(nepochs),settings)
    settings = re.sub('NEPFILL',str(nepochs-1),settings) if save else re.sub('NEPFILL',str(nepochs*2),settings)
    settings = re.sub('YDIM',str(opts['ydims'].iloc[0]),settings)
    settings = re.sub('SDIM',str(opts['sdims'].iloc[0]),settings)
    settings = re.sub('MISS_FILE',missf,settings) #if not 'medhist' in inputf else re.sub('--true_miss_file data_python/MISS_FILE','',settings)
    settings = re.sub('TYPES_FILE',typef,settings)
    settings = re.sub('SAVE_FILE',inputf,settings)
    settings = re.sub('LRATE',str(opts['lrates'].iloc[0]),settings)
    settings = re.sub('MODLOAD','1',settings) if modload else re.sub('MODLOAD','0',settings)
    
    return settings

In [2]:
sample_size=178
# get file list
files=[i for i in os.listdir('data_python/') if not '_type' in i and not '_missing' in i and i not in '.DS_Store']
files.sort()
print(files)

['ARObjectFinding.csv', 'ARPlaceAndFindTelemetryVariance.csv', 'ARScreenButtonPresses.csv', 'BITDOTMotorInstructionReadingTimeRatios.csv', 'MMSE_Attention_Concentration.csv', 'MMSE_Language.csv', 'MMSE_Memory_Recall.csv', 'MMSE_Orientation.csv', 'MMSE_Working_Memory_Registration.csv', 'MotorDrawingFeatures.csv', 'MotorTappingFeatures.csv', 'MotorTestDurations.csv']


# General settings

In [3]:
best_hyper = pd.read_csv('best_hyper_ALTOIDA_processed.csv')
best_hyper

lrates  nbatch  wdecay  ydims  \
0    0.001      16   0.001      1   
1    0.001      16   0.010      1   
2    0.010      16   0.000      1   
3    0.010      16   0.000      1   
4    0.010      32   0.010      1   
5    0.010      32   0.010      1   
6    0.001      16   0.001      1   
7    0.010      32   0.000      1   
8    0.010      32   0.001      1   
9    0.010      16   0.001      1   
10   0.010      16   0.010      1   
11   0.010      32   0.010      1   

                                          files        loss  sdims  
0                           ARObjectFinding.csv   24.957258      1  
1           ARPlaceAndFindTelemetryVariance.csv -290.294244      1  
2                     ARScreenButtonPresses.csv   22.558093      1  
3   BITDOTMotorInstructionReadingTimeRatios.csv    4.106932      1  
4              MMSE_Attention_Concentration.csv    0.910142      4  
5                             MMSE_Language.csv    0.613249      2  
6                        MMSE_Memory_Recall.csv    1.080130      3  
7                          MMSE_Orientation.csv    0.688555      4  
8          MMSE_Working_Memory_Registration.csv    0.058547      1  
9                      MotorDrawingFeatures.csv   68.877012      1  
10                     MotorTappingFeatures.csv   14.643649      1  
11                       MotorTestDurations.csv   53.503700      1

# VP decoding

Run after bnet.R

In [4]:
os.getcwd()

'/Users/meemansasood/Documents/Documents_IT/VAMBN_Version5_mmseEncoded_final/data/HI-VAE'

In [5]:
meta = pd.read_csv('metaenc.csv')
meta

scode_ARObjectFinding        SUBJID  zcode_ARObjectFinding  \
0                        0  009-20_001_1              -1.042224   
1                        0  009-20_002_1               0.128795   
2                        0  009-20_003_1               1.216998   
3                        0  009-20_004_1               0.270090   
4                        0  009-20_005_1              -0.627163   
..                     ...           ...                    ...   
173                      0     005_012_2               2.632748   
174                      0     005_012_3               2.256792   
175                      0     005_015_1               2.004861   
176                      0     005_015_2               2.142821   
177                      0     005_015_3               2.153902   

     scode_ARPlaceAndFindTelemetryVariance  \
0                                        0   
1                                        0   
2                                        0   
3                                        0   
4                                        0   
..                                     ...   
173                                      0   
174                                      0   
175                                      0   
176                                      0   
177                                      0   

     zcode_ARPlaceAndFindTelemetryVariance  scode_ARScreenButtonPresses  \
0                                 0.935868                            0   
1                                 2.264648                            0   
2                                 1.235406                            0   
3                                 2.717478                            0   
4                                 2.300178                            0   
..                                     ...                          ...   
173                               3.557675                            0   
174                               3.426479                            0   
175                               3.820880                            0   
176                               2.720714                            0   
177                               2.514126                            0   

     zcode_ARScreenButtonPresses  \
0                       0.585778   
1                      -0.106377   
2                       0.070480   
3                      -0.446318   
4                       0.156115   
..                           ...   
173                    -0.353706   
174                    -1.651626   
175                    -0.348762   
176                    -1.004784   
177                    -0.684394   

     scode_BITDOTMotorInstructionReadingTimeRatios  \
0                                                0   
1                                                0   
2                                                0   
3                                                0   
4                                                0   
..                                             ...   
173                                              0   
174                                              0   
175                                              0   
176                                              0   
177                                              0   

     zcode_BITDOTMotorInstructionReadingTimeRatios  \
0                                         0.680546   
1                                        -0.517770   
2                                         0.689196   
3                                        -0.118558   
4                                         0.362346   
..                                             ...   
173                                      -1.246386   
174                                      -1.246386   
175                                      -1.170140   
176                                      -1.170140   
177                                      -1.170140   

     scode_MMSE

In [7]:
VPcodes = pd.read_csv('/Users/meemansasood/Documents/Documents_IT/VAMBN_Version5_mmseEncoded_final/data/data_out/main_VirtualPPts_10.csv')
VPcodes

zcode_ARObjectFinding  zcode_ARPlaceAndFindTelemetryVariance  \
0                 -0.177119                               2.638057   
1                 -0.433077                               1.649321   
2                  2.442221                               2.834292   
3                  0.668548                               2.540274   
4                  0.081226                               1.502781   
...                     ...                                    ...   
1775              -0.676143                               1.987050   
1776               1.626966                               2.747440   
1777               0.865261                               1.443331   
1778               2.902551                               3.148697   
1779               0.616414                               4.687998   

      zcode_ARScreenButtonPresses  \
0                       -0.306168   
1                        0.316748   
2                       -1.162448   
3                        0.389526   
4                        0.648992   
...                           ...   
1775                     1.323556   
1776                    -0.368695   
1777                     0.128631   
1778                    -1.683484   
1779                     0.867332   

      zcode_BITDOTMotorInstructionReadingTimeRatios  \
0                                         -0.012441   
1                                         -0.794143   
2                                          0.498965   
3                                         -0.310567   
4                                          0.687618   
...                                             ...   
1775                                      -0.292694   
1776                                      -0.015869   
1777                                      -1.815757   
1778                                       0.446603   
1779                                      -0.517685   

      scode_MMSE_Attention_Concentration  zcode_MMSE_Attention_Concentration  \
0                                      2                            7.248290   
1                                      3                            0.730296   
2                                      2                            7.248290   
3                                      3                           -0.218969   
4                                      2                            7.248290   
...                                  ...                                 ...   
1775                                   2                            7.248290   
1776                                   3                           -0.498820   
1777                                   3                            1.302375   
1778                                   2                            7.248290   
1779                                   3                            0.008076   

      scode_MMSE_Language  zcode_MMSE_Language  scode_MMSE_Memory_Recall  \
0                       1             0.191511                         0   
1                       0            -7.366124                         2   
2                       0            -7.277397                         0   
3                       0            -7.400230                         2   
4                       0            -6.988706                         0   
...                   ...                  ...                       ...   
1775                    1            -0.337520                         2   
1776                    0            -7.237735                         2   
1777                    0            -7.245074                         2   
1778                    0            -7.024231                         2   
1779                    0            -7.324050                         2   

      zcode_MMSE_Memory_Recall  ...  SA_yearsOfEducation_VIS1  SA_DX_VIS1  \
0                     4.042812  ...                 19.117882           1   
1                    -1.141633 

In [8]:
VPcodes = pd.read_csv('/Users/meemansasood/Documents/Documents_IT/VAMBN_Version5_mmseEncoded_final/data/data_out/main_VirtualPPts_10.csv')
dfs=list()
virt=list()
decs=list()
sample_size=178
n=sample_size
#decoded = []
for f in files:
    # replace placeholders in template
    opts=dict(best_hyper[best_hyper['files'].copy()==f])
    opts['nbatch'].iloc[0]=sample_size
    settings=set_settings(opts,nepochs=1,modload=True,save=False)
    #run
    zcodes=VPcodes['zcode_'+re.sub('.csv','',f)]
    scodes=VPcodes['scode_'+re.sub('.csv','',f)] if 'scode_'+re.sub('.csv','',f) in VPcodes.columns else np.zeros(zcodes.shape)
    #dec=helpers.dec_network(settings,zcodes,scodes,VP=True)
    decs = pd.DataFrame()
    for i in range(int(len(VPcodes)/n)):
        dec=helpers.dec_network(settings,zcodes[i*n:(i*n+n)],scodes[i*n:(i*n+n)],VP=True);
        dec = pd.DataFrame(dec)
        #decs = np.concatenate((decs, dec), axis = 0)
        decs = decs.append(dec)
    #decs = pd.DataFrame(decs)
    subj=pd.read_csv('python_names/'+re.sub('.csv','',f)+'_subj.csv')['x']
    names=pd.read_csv('python_names/'+re.sub('.csv','',f)+'_cols.csv')['x']
    dat=pd.DataFrame(decs)
    dat.columns=names
    dat['SUBJID']=list(range(len(dat)))
    #dat =dat.assign(SUBJID=list(range(len(dat[1]))))
    virt.append(decs)
    dfs.append(dat)


decoded=helpers.merge_dat(dfs)
decoded.to_csv('decodedVP_10.csv',index=False)

[*] Importing model: model_HIVAE_inputDropout
[*] Defining placeholders




/Users/meemansasood/Library/Python/3.7/lib/python/site-packages/pandas/core/indexing.py:691: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value, self.name)


[*] Defining Encoder...
Instructions for updating:
Use keras.layers.Dense instead.
Instructions for updating:
Please use `layer.__call__` method instead.


[*] Defining Decoder...
Instructions for updating:

Future major versions of TensorFlow will allow gradients to flow
into the labels input on backprop by default.

See `tf.nn.softmax_cross_entropy_with_logits_v2`.

The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

Instructions for updating:
The TensorFlow Distributions library has moved to TensorFlow Probability (https://github.com/tensorflow/probability). You should update all references to use `tfp.distributions` instead of `tf.distributions`.
Instructions for updating:
Th

[*] Defining Encoder...
[*] Defining Decoder...
[*] Defining Cost function...
INFO:tensorflow:Restoring parameters from ./Saved_Networks/ARObjectFinding/ARObjectFinding.ckpt
Model restored: ./Saved_Networks/ARObjectFinding/ARObjectFinding.ckpt
::::::DECODING:::::::::
::::::::::::VP_misslist/ARObjectFinding_vpmiss.csv
memememe
[[ 1.          1.         62.859      ...  7.          0.
   0.        ]
 [ 0.          1.         11.799      ...  3.          0.
   0.        ]
 [ 0.          0.         15.60733333 ...  1.          0.
   0.        ]
 ...
 [ 0.          0.          6.79266667 ...  2.          0.
   0.        ]
 [ 0.          0.         10.06866667 ...  0.          0.
   0.        ]
 [ 0.          0.         13.09933333 ...  0.          0.
   0.        ]]
memememe
[[ 1.          1.         62.859      ...  7.          0.
   0.        ]
 [ 0.          1.         11.799      ...  3.          0.
   0.        ]
 [ 0.          0.         15.60733333 ...  1.          0.
   0.        ]


[*] Defining Encoder...
[*] Defining Decoder...
[*] Defining Cost function...
INFO:tensorflow:Restoring parameters from ./Saved_Networks/ARObjectFinding/ARObjectFinding.ckpt
Model restored: ./Saved_Networks/ARObjectFinding/ARObjectFinding.ckpt
::::::DECODING:::::::::
::::::::::::VP_misslist/ARObjectFinding_vpmiss.csv
memememe
[[ 1.          1.         62.859      ...  7.          0.
   0.        ]
 [ 0.          1.         11.799      ...  3.          0.
   0.        ]
 [ 0.          0.         15.60733333 ...  1.          0.
   0.        ]
 ...
 [ 0.          0.          6.79266667 ...  2.          0.
   0.        ]
 [ 0.          0.         10.06866667 ...  0.          0.
   0.        ]
 [ 0.          0.         13.09933333 ...  0.          0.
   0.        ]]
memememe
[[ 1.          1.         62.859      ...  7.          0.
   0.        ]
 [ 0.          1.         11.799      ...  3.          0.
   0.        ]
 [ 0.          0.         15.60733333 ...  1.          0.
   0.        ]


[*] Defining Encoder...
[*] Defining Decoder...
[*] Defining Cost function...
INFO:tensorflow:Restoring parameters from ./Saved_Networks/ARObjectFinding/ARObjectFinding.ckpt
Model restored: ./Saved_Networks/ARObjectFinding/ARObjectFinding.ckpt
::::::DECODING:::::::::
::::::::::::VP_misslist/ARObjectFinding_vpmiss.csv
memememe
[[ 1.          1.         62.859      ...  7.          0.
   0.        ]
 [ 0.          1.         11.799      ...  3.          0.
   0.        ]
 [ 0.          0.         15.60733333 ...  1.          0.
   0.        ]
 ...
 [ 0.          0.          6.79266667 ...  2.          0.
   0.        ]
 [ 0.          0.         10.06866667 ...  0.          0.
   0.        ]
 [ 0.          0.         13.09933333 ...  0.          0.
   0.        ]]
memememe
[[ 1.          1.         62.859      ...  7.          0.
   0.        ]
 [ 0.          1.         11.799      ...  3.          0.
   0.        ]
 [ 0.          0.         15.60733333 ...  1.          0.
   0.        ]


[*] Defining Encoder...
[*] Defining Decoder...
[*] Defining Cost function...
INFO:tensorflow:Restoring parameters from ./Saved_Networks/ARObjectFinding/ARObjectFinding.ckpt
Model restored: ./Saved_Networks/ARObjectFinding/ARObjectFinding.ckpt
::::::DECODING:::::::::
::::::::::::VP_misslist/ARObjectFinding_vpmiss.csv
memememe
[[ 1.          1.         62.859      ...  7.          0.
   0.        ]
 [ 0.          1.         11.799      ...  3.          0.
   0.        ]
 [ 0.          0.         15.60733333 ...  1.          0.
   0.        ]
 ...
 [ 0.          0.          6.79266667 ...  2.          0.
   0.        ]
 [ 0.          0.         10.06866667 ...  0.          0.
   0.        ]
 [ 0.          0.         13.09933333 ...  0.          0.
   0.        ]]
memememe
[[ 1.          1.         62.859      ...  7.          0.
   0.        ]
 [ 0.          1.         11.799      ...  3.          0.
   0.        ]
 [ 0.          0.         15.60733333 ...  1.          0.
   0.        ]


[*] Defining Encoder...
[*] Defining Decoder...
[*] Defining Cost function...
INFO:tensorflow:Restoring parameters from ./Saved_Networks/ARObjectFinding/ARObjectFinding.ckpt
Model restored: ./Saved_Networks/ARObjectFinding/ARObjectFinding.ckpt
::::::DECODING:::::::::
::::::::::::VP_misslist/ARObjectFinding_vpmiss.csv
memememe
[[ 1.          1.         62.859      ...  7.          0.
   0.        ]
 [ 0.          1.         11.799      ...  3.          0.
   0.        ]
 [ 0.          0.         15.60733333 ...  1.          0.
   0.        ]
 ...
 [ 0.          0.          6.79266667 ...  2.          0.
   0.        ]
 [ 0.          0.         10.06866667 ...  0.          0.
   0.        ]
 [ 0.          0.         13.09933333 ...  0.          0.
   0.        ]]
memememe
[[ 1.          1.         62.859      ...  7.          0.
   0.        ]
 [ 0.          1.         11.799      ...  3.          0.
   0.        ]
 [ 0.          0.         15.60733333 ...  1.          0.
   0.        ]


/Users/meemansasood/Library/Python/3.7/lib/python/site-packages/pandas/core/indexing.py:691: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value, self.name)


[*] Defining Encoder...
[*] Defining Decoder...
[*] Defining Cost function...
INFO:tensorflow:Restoring parameters from ./Saved_Networks/ARPlaceAndFindTelemetryVariance/ARPlaceAndFindTelemetryVariance.ckpt
Model restored: ./Saved_Networks/ARPlaceAndFindTelemetryVariance/ARPlaceAndFindTelemetryVariance.ckpt
::::::DECODING:::::::::
::::::::::::VP_misslist/ARPlaceAndFindTelemetryVariance_vpmiss.csv
memememe
[[1.13858763e-02 1.71628473e-02 1.18008802e-02 ...            nan
             nan            nan]
 [8.14907130e-02 1.43892881e-02 1.43878368e-01 ...            nan
             nan            nan]
 [7.06299919e-03 1.06101326e-02 7.64586552e-02 ... 1.21709101e-02
  2.29202948e+00 5.51916067e-02]
 ...
 [1.77004373e-02 1.64988965e-02 1.57841988e-02 ... 2.15204498e-04
  2.17061528e+00 4.12259607e-03]
 [4.77064835e-02 3.01781887e-03 1.23512438e-02 ... 2.66994504e-04
  1.87030608e+00 2.76410228e-04]
 [5.82071885e-03 3.63120717e-02 2.93137942e-02 ... 7.45505713e-04
  4.63724492e+00 2.5047382

[*] Importing model: model_HIVAE_inputDropout
[*] Defining placeholders
[*] Defining Encoder...
[*] Defining Decoder...
[*] Defining Cost function...
INFO:tensorflow:Restoring parameters from ./Saved_Networks/ARPlaceAndFindTelemetryVariance/ARPlaceAndFindTelemetryVariance.ckpt
Model restored: ./Saved_Networks/ARPlaceAndFindTelemetryVariance/ARPlaceAndFindTelemetryVariance.ckpt
::::::DECODING:::::::::
::::::::::::VP_misslist/ARPlaceAndFindTelemetryVariance_vpmiss.csv
memememe
[[1.13858763e-02 1.71628473e-02 1.18008802e-02 ...            nan
             nan            nan]
 [8.14907130e-02 1.43892881e-02 1.43878368e-01 ...            nan
             nan            nan]
 [7.06299919e-03 1.06101326e-02 7.64586552e-02 ... 1.21709101e-02
  2.29202948e+00 5.51916067e-02]
 ...
 [1.77004373e-02 1.64988965e-02 1.57841988e-02 ... 2.15204498e-04
  2.17061528e+00 4.12259607e-03]
 [4.77064835e-02 3.01781887e-03 1.23512438e-02 ... 2.66994504e-04
  1.87030608e+00 2.76410228e-04]
 [5.82071885e-03 3.6

[*] Importing model: model_HIVAE_inputDropout
[*] Defining placeholders
[*] Defining Encoder...
[*] Defining Decoder...
[*] Defining Cost function...
INFO:tensorflow:Restoring parameters from ./Saved_Networks/ARPlaceAndFindTelemetryVariance/ARPlaceAndFindTelemetryVariance.ckpt
Model restored: ./Saved_Networks/ARPlaceAndFindTelemetryVariance/ARPlaceAndFindTelemetryVariance.ckpt
::::::DECODING:::::::::
::::::::::::VP_misslist/ARPlaceAndFindTelemetryVariance_vpmiss.csv
memememe
[[1.13858763e-02 1.71628473e-02 1.18008802e-02 ...            nan
             nan            nan]
 [8.14907130e-02 1.43892881e-02 1.43878368e-01 ...            nan
             nan            nan]
 [7.06299919e-03 1.06101326e-02 7.64586552e-02 ... 1.21709101e-02
  2.29202948e+00 5.51916067e-02]
 ...
 [1.77004373e-02 1.64988965e-02 1.57841988e-02 ... 2.15204498e-04
  2.17061528e+00 4.12259607e-03]
 [4.77064835e-02 3.01781887e-03 1.23512438e-02 ... 2.66994504e-04
  1.87030608e+00 2.76410228e-04]
 [5.82071885e-03 3.6

[*] Importing model: model_HIVAE_inputDropout
[*] Defining placeholders
[*] Defining Encoder...
[*] Defining Decoder...
[*] Defining Cost function...
INFO:tensorflow:Restoring parameters from ./Saved_Networks/ARPlaceAndFindTelemetryVariance/ARPlaceAndFindTelemetryVariance.ckpt
Model restored: ./Saved_Networks/ARPlaceAndFindTelemetryVariance/ARPlaceAndFindTelemetryVariance.ckpt
::::::DECODING:::::::::
::::::::::::VP_misslist/ARPlaceAndFindTelemetryVariance_vpmiss.csv
memememe
[[1.13858763e-02 1.71628473e-02 1.18008802e-02 ...            nan
             nan            nan]
 [8.14907130e-02 1.43892881e-02 1.43878368e-01 ...            nan
             nan            nan]
 [7.06299919e-03 1.06101326e-02 7.64586552e-02 ... 1.21709101e-02
  2.29202948e+00 5.51916067e-02]
 ...
 [1.77004373e-02 1.64988965e-02 1.57841988e-02 ... 2.15204498e-04
  2.17061528e+00 4.12259607e-03]
 [4.77064835e-02 3.01781887e-03 1.23512438e-02 ... 2.66994504e-04
  1.87030608e+00 2.76410228e-04]
 [5.82071885e-03 3.6

[*] Importing model: model_HIVAE_inputDropout
[*] Defining placeholders
[*] Defining Encoder...
[*] Defining Decoder...
[*] Defining Cost function...
INFO:tensorflow:Restoring parameters from ./Saved_Networks/ARPlaceAndFindTelemetryVariance/ARPlaceAndFindTelemetryVariance.ckpt
Model restored: ./Saved_Networks/ARPlaceAndFindTelemetryVariance/ARPlaceAndFindTelemetryVariance.ckpt
::::::DECODING:::::::::
::::::::::::VP_misslist/ARPlaceAndFindTelemetryVariance_vpmiss.csv
memememe
[[1.13858763e-02 1.71628473e-02 1.18008802e-02 ...            nan
             nan            nan]
 [8.14907130e-02 1.43892881e-02 1.43878368e-01 ...            nan
             nan            nan]
 [7.06299919e-03 1.06101326e-02 7.64586552e-02 ... 1.21709101e-02
  2.29202948e+00 5.51916067e-02]
 ...
 [1.77004373e-02 1.64988965e-02 1.57841988e-02 ... 2.15204498e-04
  2.17061528e+00 4.12259607e-03]
 [4.77064835e-02 3.01781887e-03 1.23512438e-02 ... 2.66994504e-04
  1.87030608e+00 2.76410228e-04]
 [5.82071885e-03 3.6

[*] Importing model: model_HIVAE_inputDropout
[*] Defining placeholders
[*] Defining Encoder...
[*] Defining Decoder...
[*] Defining Cost function...
INFO:tensorflow:Restoring parameters from ./Saved_Networks/ARPlaceAndFindTelemetryVariance/ARPlaceAndFindTelemetryVariance.ckpt
Model restored: ./Saved_Networks/ARPlaceAndFindTelemetryVariance/ARPlaceAndFindTelemetryVariance.ckpt
::::::DECODING:::::::::
::::::::::::VP_misslist/ARPlaceAndFindTelemetryVariance_vpmiss.csv
memememe
[[1.13858763e-02 1.71628473e-02 1.18008802e-02 ...            nan
             nan            nan]
 [8.14907130e-02 1.43892881e-02 1.43878368e-01 ...            nan
             nan            nan]
 [7.06299919e-03 1.06101326e-02 7.64586552e-02 ... 1.21709101e-02
  2.29202948e+00 5.51916067e-02]
 ...
 [1.77004373e-02 1.64988965e-02 1.57841988e-02 ... 2.15204498e-04
  2.17061528e+00 4.12259607e-03]
 [4.77064835e-02 3.01781887e-03 1.23512438e-02 ... 2.66994504e-04
  1.87030608e+00 2.76410228e-04]
 [5.82071885e-03 3.6

[*] Importing model: model_HIVAE_inputDropout
[*] Defining placeholders
[*] Defining Encoder...
[*] Defining Decoder...
[*] Defining Cost function...
INFO:tensorflow:Restoring parameters from ./Saved_Networks/ARPlaceAndFindTelemetryVariance/ARPlaceAndFindTelemetryVariance.ckpt
Model restored: ./Saved_Networks/ARPlaceAndFindTelemetryVariance/ARPlaceAndFindTelemetryVariance.ckpt
::::::DECODING:::::::::
::::::::::::VP_misslist/ARPlaceAndFindTelemetryVariance_vpmiss.csv
memememe
[[1.13858763e-02 1.71628473e-02 1.18008802e-02 ...            nan
             nan            nan]
 [8.14907130e-02 1.43892881e-02 1.43878368e-01 ...            nan
             nan            nan]
 [7.06299919e-03 1.06101326e-02 7.64586552e-02 ... 1.21709101e-02
  2.29202948e+00 5.51916067e-02]
 ...
 [1.77004373e-02 1.64988965e-02 1.57841988e-02 ... 2.15204498e-04
  2.17061528e+00 4.12259607e-03]
 [4.77064835e-02 3.01781887e-03 1.23512438e-02 ... 2.66994504e-04
  1.87030608e+00 2.76410228e-04]
 [5.82071885e-03 3.6

[*] Importing model: model_HIVAE_inputDropout
[*] Defining placeholders
[*] Defining Encoder...
[*] Defining Decoder...
[*] Defining Cost function...
INFO:tensorflow:Restoring parameters from ./Saved_Networks/ARPlaceAndFindTelemetryVariance/ARPlaceAndFindTelemetryVariance.ckpt
Model restored: ./Saved_Networks/ARPlaceAndFindTelemetryVariance/ARPlaceAndFindTelemetryVariance.ckpt
::::::DECODING:::::::::
::::::::::::VP_misslist/ARPlaceAndFindTelemetryVariance_vpmiss.csv
memememe
[[1.13858763e-02 1.71628473e-02 1.18008802e-02 ...            nan
             nan            nan]
 [8.14907130e-02 1.43892881e-02 1.43878368e-01 ...            nan
             nan            nan]
 [7.06299919e-03 1.06101326e-02 7.64586552e-02 ... 1.21709101e-02
  2.29202948e+00 5.51916067e-02]
 ...
 [1.77004373e-02 1.64988965e-02 1.57841988e-02 ... 2.15204498e-04
  2.17061528e+00 4.12259607e-03]
 [4.77064835e-02 3.01781887e-03 1.23512438e-02 ... 2.66994504e-04
  1.87030608e+00 2.76410228e-04]
 [5.82071885e-03 3.6

[*] Importing model: model_HIVAE_inputDropout
[*] Defining placeholders
[*] Defining Encoder...
[*] Defining Decoder...
[*] Defining Cost function...
INFO:tensorflow:Restoring parameters from ./Saved_Networks/ARPlaceAndFindTelemetryVariance/ARPlaceAndFindTelemetryVariance.ckpt
Model restored: ./Saved_Networks/ARPlaceAndFindTelemetryVariance/ARPlaceAndFindTelemetryVariance.ckpt
::::::DECODING:::::::::
::::::::::::VP_misslist/ARPlaceAndFindTelemetryVariance_vpmiss.csv
memememe
[[1.13858763e-02 1.71628473e-02 1.18008802e-02 ...            nan
             nan            nan]
 [8.14907130e-02 1.43892881e-02 1.43878368e-01 ...            nan
             nan            nan]
 [7.06299919e-03 1.06101326e-02 7.64586552e-02 ... 1.21709101e-02
  2.29202948e+00 5.51916067e-02]
 ...
 [1.77004373e-02 1.64988965e-02 1.57841988e-02 ... 2.15204498e-04
  2.17061528e+00 4.12259607e-03]
 [4.77064835e-02 3.01781887e-03 1.23512438e-02 ... 2.66994504e-04
  1.87030608e+00 2.76410228e-04]
 [5.82071885e-03 3.6

[*] Importing model: model_HIVAE_inputDropout
[*] Defining placeholders
[*] Defining Encoder...
[*] Defining Decoder...
[*] Defining Cost function...
INFO:tensorflow:Restoring parameters from ./Saved_Networks/ARPlaceAndFindTelemetryVariance/ARPlaceAndFindTelemetryVariance.ckpt
Model restored: ./Saved_Networks/ARPlaceAndFindTelemetryVariance/ARPlaceAndFindTelemetryVariance.ckpt
::::::DECODING:::::::::
::::::::::::VP_misslist/ARPlaceAndFindTelemetryVariance_vpmiss.csv
memememe
[[1.13858763e-02 1.71628473e-02 1.18008802e-02 ...            nan
             nan            nan]
 [8.14907130e-02 1.43892881e-02 1.43878368e-01 ...            nan
             nan            nan]
 [7.06299919e-03 1.06101326e-02 7.64586552e-02 ... 1.21709101e-02
  2.29202948e+00 5.51916067e-02]
 ...
 [1.77004373e-02 1.64988965e-02 1.57841988e-02 ... 2.15204498e-04
  2.17061528e+00 4.12259607e-03]
 [4.77064835e-02 3.01781887e-03 1.23512438e-02 ... 2.66994504e-04
  1.87030608e+00 2.76410228e-04]
 [5.82071885e-03 3.6

/Users/meemansasood/Library/Python/3.7/lib/python/site-packages/pandas/core/indexing.py:691: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value, self.name)


[*] Importing model: model_HIVAE_inputDropout
[*] Defining placeholders
[*] Defining Encoder...
[*] Defining Decoder...
[*] Defining Cost function...
INFO:tensorflow:Restoring parameters from ./Saved_Networks/ARScreenButtonPresses/ARScreenButtonPresses.ckpt
Model restored: ./Saved_Networks/ARScreenButtonPresses/ARScreenButtonPresses.ckpt
::::::DECODING:::::::::
::::::::::::VP_misslist/ARScreenButtonPresses_vpmiss.csv
memememe
[[1.28900000e+00 6.47200854e-02 0.00000000e+00 ... 3.00000000e+00
  0.00000000e+00 1.00000000e+02]
 [           nan            nan 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 1.00000000e+02]
 [8.74500000e-01 1.83182421e-01 0.00000000e+00 ... 1.00000000e+00
  0.00000000e+00 1.00000000e+02]
 ...
 [1.08150000e+00 1.59567779e-01 1.00000000e+00 ... 0.00000000e+00
  1.00000000e+00 1.00000000e+02]
 [9.03166667e-01 2.86278825e-01 0.00000000e+00 ... 3.00000000e+00
  2.00000000e+00 1.00000000e+02]
 [1.15316667e+00 3.55056869e-01 0.00000000e+00 ... 0.00000000e+00
  2.

[*] Defining Encoder...
[*] Defining Decoder...
[*] Defining Cost function...
INFO:tensorflow:Restoring parameters from ./Saved_Networks/ARScreenButtonPresses/ARScreenButtonPresses.ckpt
Model restored: ./Saved_Networks/ARScreenButtonPresses/ARScreenButtonPresses.ckpt
::::::DECODING:::::::::
::::::::::::VP_misslist/ARScreenButtonPresses_vpmiss.csv
memememe
[[1.28900000e+00 6.47200854e-02 0.00000000e+00 ... 3.00000000e+00
  0.00000000e+00 1.00000000e+02]
 [           nan            nan 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 1.00000000e+02]
 [8.74500000e-01 1.83182421e-01 0.00000000e+00 ... 1.00000000e+00
  0.00000000e+00 1.00000000e+02]
 ...
 [1.08150000e+00 1.59567779e-01 1.00000000e+00 ... 0.00000000e+00
  1.00000000e+00 1.00000000e+02]
 [9.03166667e-01 2.86278825e-01 0.00000000e+00 ... 3.00000000e+00
  2.00000000e+00 1.00000000e+02]
 [1.15316667e+00 3.55056869e-01 0.00000000e+00 ... 0.00000000e+00
  2.00000000e+00            nan]]
memememe
[[1.28900000e+00 6.47200854e-02 0

[*] Defining Encoder...
[*] Defining Decoder...
[*] Defining Cost function...
INFO:tensorflow:Restoring parameters from ./Saved_Networks/ARScreenButtonPresses/ARScreenButtonPresses.ckpt
Model restored: ./Saved_Networks/ARScreenButtonPresses/ARScreenButtonPresses.ckpt
::::::DECODING:::::::::
::::::::::::VP_misslist/ARScreenButtonPresses_vpmiss.csv
memememe
[[1.28900000e+00 6.47200854e-02 0.00000000e+00 ... 3.00000000e+00
  0.00000000e+00 1.00000000e+02]
 [           nan            nan 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 1.00000000e+02]
 [8.74500000e-01 1.83182421e-01 0.00000000e+00 ... 1.00000000e+00
  0.00000000e+00 1.00000000e+02]
 ...
 [1.08150000e+00 1.59567779e-01 1.00000000e+00 ... 0.00000000e+00
  1.00000000e+00 1.00000000e+02]
 [9.03166667e-01 2.86278825e-01 0.00000000e+00 ... 3.00000000e+00
  2.00000000e+00 1.00000000e+02]
 [1.15316667e+00 3.55056869e-01 0.00000000e+00 ... 0.00000000e+00
  2.00000000e+00            nan]]
memememe
[[1.28900000e+00 6.47200854e-02 0

[*] Defining Encoder...
[*] Defining Decoder...
[*] Defining Cost function...
INFO:tensorflow:Restoring parameters from ./Saved_Networks/ARScreenButtonPresses/ARScreenButtonPresses.ckpt
Model restored: ./Saved_Networks/ARScreenButtonPresses/ARScreenButtonPresses.ckpt
::::::DECODING:::::::::
::::::::::::VP_misslist/ARScreenButtonPresses_vpmiss.csv
memememe
[[1.28900000e+00 6.47200854e-02 0.00000000e+00 ... 3.00000000e+00
  0.00000000e+00 1.00000000e+02]
 [           nan            nan 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 1.00000000e+02]
 [8.74500000e-01 1.83182421e-01 0.00000000e+00 ... 1.00000000e+00
  0.00000000e+00 1.00000000e+02]
 ...
 [1.08150000e+00 1.59567779e-01 1.00000000e+00 ... 0.00000000e+00
  1.00000000e+00 1.00000000e+02]
 [9.03166667e-01 2.86278825e-01 0.00000000e+00 ... 3.00000000e+00
  2.00000000e+00 1.00000000e+02]
 [1.15316667e+00 3.55056869e-01 0.00000000e+00 ... 0.00000000e+00
  2.00000000e+00            nan]]
memememe
[[1.28900000e+00 6.47200854e-02 0

[*] Defining Encoder...
[*] Defining Decoder...
[*] Defining Cost function...
INFO:tensorflow:Restoring parameters from ./Saved_Networks/ARScreenButtonPresses/ARScreenButtonPresses.ckpt
Model restored: ./Saved_Networks/ARScreenButtonPresses/ARScreenButtonPresses.ckpt
::::::DECODING:::::::::
::::::::::::VP_misslist/ARScreenButtonPresses_vpmiss.csv
memememe
[[1.28900000e+00 6.47200854e-02 0.00000000e+00 ... 3.00000000e+00
  0.00000000e+00 1.00000000e+02]
 [           nan            nan 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 1.00000000e+02]
 [8.74500000e-01 1.83182421e-01 0.00000000e+00 ... 1.00000000e+00
  0.00000000e+00 1.00000000e+02]
 ...
 [1.08150000e+00 1.59567779e-01 1.00000000e+00 ... 0.00000000e+00
  1.00000000e+00 1.00000000e+02]
 [9.03166667e-01 2.86278825e-01 0.00000000e+00 ... 3.00000000e+00
  2.00000000e+00 1.00000000e+02]
 [1.15316667e+00 3.55056869e-01 0.00000000e+00 ... 0.00000000e+00
  2.00000000e+00            nan]]
memememe
[[1.28900000e+00 6.47200854e-02 0

[*] Defining Encoder...
[*] Defining Decoder...
[*] Defining Cost function...
INFO:tensorflow:Restoring parameters from ./Saved_Networks/ARScreenButtonPresses/ARScreenButtonPresses.ckpt
Model restored: ./Saved_Networks/ARScreenButtonPresses/ARScreenButtonPresses.ckpt
::::::DECODING:::::::::
::::::::::::VP_misslist/ARScreenButtonPresses_vpmiss.csv
memememe
[[1.28900000e+00 6.47200854e-02 0.00000000e+00 ... 3.00000000e+00
  0.00000000e+00 1.00000000e+02]
 [           nan            nan 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 1.00000000e+02]
 [8.74500000e-01 1.83182421e-01 0.00000000e+00 ... 1.00000000e+00
  0.00000000e+00 1.00000000e+02]
 ...
 [1.08150000e+00 1.59567779e-01 1.00000000e+00 ... 0.00000000e+00
  1.00000000e+00 1.00000000e+02]
 [9.03166667e-01 2.86278825e-01 0.00000000e+00 ... 3.00000000e+00
  2.00000000e+00 1.00000000e+02]
 [1.15316667e+00 3.55056869e-01 0.00000000e+00 ... 0.00000000e+00
  2.00000000e+00            nan]]
memememe
[[1.28900000e+00 6.47200854e-02 0

[*] Defining Encoder...
[*] Defining Decoder...
[*] Defining Cost function...
INFO:tensorflow:Restoring parameters from ./Saved_Networks/ARScreenButtonPresses/ARScreenButtonPresses.ckpt
Model restored: ./Saved_Networks/ARScreenButtonPresses/ARScreenButtonPresses.ckpt
::::::DECODING:::::::::
::::::::::::VP_misslist/ARScreenButtonPresses_vpmiss.csv
memememe
[[1.28900000e+00 6.47200854e-02 0.00000000e+00 ... 3.00000000e+00
  0.00000000e+00 1.00000000e+02]
 [           nan            nan 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 1.00000000e+02]
 [8.74500000e-01 1.83182421e-01 0.00000000e+00 ... 1.00000000e+00
  0.00000000e+00 1.00000000e+02]
 ...
 [1.08150000e+00 1.59567779e-01 1.00000000e+00 ... 0.00000000e+00
  1.00000000e+00 1.00000000e+02]
 [9.03166667e-01 2.86278825e-01 0.00000000e+00 ... 3.00000000e+00
  2.00000000e+00 1.00000000e+02]
 [1.15316667e+00 3.55056869e-01 0.00000000e+00 ... 0.00000000e+00
  2.00000000e+00            nan]]
memememe
[[1.28900000e+00 6.47200854e-02 0

[*] Defining Encoder...
[*] Defining Decoder...
[*] Defining Cost function...
INFO:tensorflow:Restoring parameters from ./Saved_Networks/ARScreenButtonPresses/ARScreenButtonPresses.ckpt
Model restored: ./Saved_Networks/ARScreenButtonPresses/ARScreenButtonPresses.ckpt
::::::DECODING:::::::::
::::::::::::VP_misslist/ARScreenButtonPresses_vpmiss.csv
memememe
[[1.28900000e+00 6.47200854e-02 0.00000000e+00 ... 3.00000000e+00
  0.00000000e+00 1.00000000e+02]
 [           nan            nan 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 1.00000000e+02]
 [8.74500000e-01 1.83182421e-01 0.00000000e+00 ... 1.00000000e+00
  0.00000000e+00 1.00000000e+02]
 ...
 [1.08150000e+00 1.59567779e-01 1.00000000e+00 ... 0.00000000e+00
  1.00000000e+00 1.00000000e+02]
 [9.03166667e-01 2.86278825e-01 0.00000000e+00 ... 3.00000000e+00
  2.00000000e+00 1.00000000e+02]
 [1.15316667e+00 3.55056869e-01 0.00000000e+00 ... 0.00000000e+00
  2.00000000e+00            nan]]
memememe
[[1.28900000e+00 6.47200854e-02 0

[*] Defining Encoder...
[*] Defining Decoder...
[*] Defining Cost function...
INFO:tensorflow:Restoring parameters from ./Saved_Networks/ARScreenButtonPresses/ARScreenButtonPresses.ckpt
Model restored: ./Saved_Networks/ARScreenButtonPresses/ARScreenButtonPresses.ckpt
::::::DECODING:::::::::
::::::::::::VP_misslist/ARScreenButtonPresses_vpmiss.csv
memememe
[[1.28900000e+00 6.47200854e-02 0.00000000e+00 ... 3.00000000e+00
  0.00000000e+00 1.00000000e+02]
 [           nan            nan 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 1.00000000e+02]
 [8.74500000e-01 1.83182421e-01 0.00000000e+00 ... 1.00000000e+00
  0.00000000e+00 1.00000000e+02]
 ...
 [1.08150000e+00 1.59567779e-01 1.00000000e+00 ... 0.00000000e+00
  1.00000000e+00 1.00000000e+02]
 [9.03166667e-01 2.86278825e-01 0.00000000e+00 ... 3.00000000e+00
  2.00000000e+00 1.00000000e+02]
 [1.15316667e+00 3.55056869e-01 0.00000000e+00 ... 0.00000000e+00
  2.00000000e+00            nan]]
memememe
[[1.28900000e+00 6.47200854e-02 0

[*] Defining Encoder...
[*] Defining Decoder...
[*] Defining Cost function...
INFO:tensorflow:Restoring parameters from ./Saved_Networks/ARScreenButtonPresses/ARScreenButtonPresses.ckpt
Model restored: ./Saved_Networks/ARScreenButtonPresses/ARScreenButtonPresses.ckpt
::::::DECODING:::::::::
::::::::::::VP_misslist/ARScreenButtonPresses_vpmiss.csv
memememe
[[1.28900000e+00 6.47200854e-02 0.00000000e+00 ... 3.00000000e+00
  0.00000000e+00 1.00000000e+02]
 [           nan            nan 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 1.00000000e+02]
 [8.74500000e-01 1.83182421e-01 0.00000000e+00 ... 1.00000000e+00
  0.00000000e+00 1.00000000e+02]
 ...
 [1.08150000e+00 1.59567779e-01 1.00000000e+00 ... 0.00000000e+00
  1.00000000e+00 1.00000000e+02]
 [9.03166667e-01 2.86278825e-01 0.00000000e+00 ... 3.00000000e+00
  2.00000000e+00 1.00000000e+02]
 [1.15316667e+00 3.55056869e-01 0.00000000e+00 ... 0.00000000e+00
  2.00000000e+00            nan]]
memememe
[[1.28900000e+00 6.47200854e-02 0

/Users/meemansasood/Library/Python/3.7/lib/python/site-packages/pandas/core/indexing.py:691: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value, self.name)


[*] Defining Cost function...
INFO:tensorflow:Restoring parameters from ./Saved_Networks/BITDOTMotorInstructionReadingTimeRatios/BITDOTMotorInstructionReadingTimeRatios.ckpt
Model restored: ./Saved_Networks/BITDOTMotorInstructionReadingTimeRatios/BITDOTMotorInstructionReadingTimeRatios.ckpt
::::::DECODING:::::::::
::::::::::::VP_misslist/BITDOTMotorInstructionReadingTimeRatios_vpmiss.csv
memememe
[[1.30364372 0.55843653 1.27608347 0.78163654 0.81343284 1.30301129]
 [2.07018897 2.19565217 1.07587253 1.06777108 1.58941948 0.39647026]
 [0.91590074 0.78507993 0.97004608 0.68697343 1.03609155 0.90875576]
 ...
 [2.81993958 1.57083333 1.12181818 1.65554465 5.23010753 1.76705049]
 [2.81993958 1.57083333 1.12181818 1.65554465 5.23010753 1.76705049]
 [2.81993958 1.57083333 1.12181818 1.65554465 5.23010753 1.76705049]]
memememe
[[1.30364372 0.55843653 1.27608347 0.78163654 0.81343284 1.30301129]
 [2.07018897 2.19565217 1.07587253 1.06777108 1.58941948 0.39647026]
 [0.91590074 0.78507993 0.9700460

[*] Defining Encoder...
[*] Defining Decoder...
[*] Defining Cost function...
INFO:tensorflow:Restoring parameters from ./Saved_Networks/BITDOTMotorInstructionReadingTimeRatios/BITDOTMotorInstructionReadingTimeRatios.ckpt
Model restored: ./Saved_Networks/BITDOTMotorInstructionReadingTimeRatios/BITDOTMotorInstructionReadingTimeRatios.ckpt
::::::DECODING:::::::::
::::::::::::VP_misslist/BITDOTMotorInstructionReadingTimeRatios_vpmiss.csv
memememe
[[1.30364372 0.55843653 1.27608347 0.78163654 0.81343284 1.30301129]
 [2.07018897 2.19565217 1.07587253 1.06777108 1.58941948 0.39647026]
 [0.91590074 0.78507993 0.97004608 0.68697343 1.03609155 0.90875576]
 ...
 [2.81993958 1.57083333 1.12181818 1.65554465 5.23010753 1.76705049]
 [2.81993958 1.57083333 1.12181818 1.65554465 5.23010753 1.76705049]
 [2.81993958 1.57083333 1.12181818 1.65554465 5.23010753 1.76705049]]
memememe
[[1.30364372 0.55843653 1.27608347 0.78163654 0.81343284 1.30301129]
 [2.07018897 2.19565217 1.07587253 1.06777108 1.589419

[*] Defining Encoder...
[*] Defining Decoder...
[*] Defining Cost function...
INFO:tensorflow:Restoring parameters from ./Saved_Networks/BITDOTMotorInstructionReadingTimeRatios/BITDOTMotorInstructionReadingTimeRatios.ckpt
Model restored: ./Saved_Networks/BITDOTMotorInstructionReadingTimeRatios/BITDOTMotorInstructionReadingTimeRatios.ckpt
::::::DECODING:::::::::
::::::::::::VP_misslist/BITDOTMotorInstructionReadingTimeRatios_vpmiss.csv
memememe
[[1.30364372 0.55843653 1.27608347 0.78163654 0.81343284 1.30301129]
 [2.07018897 2.19565217 1.07587253 1.06777108 1.58941948 0.39647026]
 [0.91590074 0.78507993 0.97004608 0.68697343 1.03609155 0.90875576]
 ...
 [2.81993958 1.57083333 1.12181818 1.65554465 5.23010753 1.76705049]
 [2.81993958 1.57083333 1.12181818 1.65554465 5.23010753 1.76705049]
 [2.81993958 1.57083333 1.12181818 1.65554465 5.23010753 1.76705049]]
memememe
[[1.30364372 0.55843653 1.27608347 0.78163654 0.81343284 1.30301129]
 [2.07018897 2.19565217 1.07587253 1.06777108 1.589419

[*] Importing model: model_HIVAE_inputDropout
[*] Defining placeholders
[*] Defining Encoder...
[*] Defining Decoder...
[*] Defining Cost function...
INFO:tensorflow:Restoring parameters from ./Saved_Networks/BITDOTMotorInstructionReadingTimeRatios/BITDOTMotorInstructionReadingTimeRatios.ckpt
Model restored: ./Saved_Networks/BITDOTMotorInstructionReadingTimeRatios/BITDOTMotorInstructionReadingTimeRatios.ckpt
::::::DECODING:::::::::
::::::::::::VP_misslist/BITDOTMotorInstructionReadingTimeRatios_vpmiss.csv
memememe
[[1.30364372 0.55843653 1.27608347 0.78163654 0.81343284 1.30301129]
 [2.07018897 2.19565217 1.07587253 1.06777108 1.58941948 0.39647026]
 [0.91590074 0.78507993 0.97004608 0.68697343 1.03609155 0.90875576]
 ...
 [2.81993958 1.57083333 1.12181818 1.65554465 5.23010753 1.76705049]
 [2.81993958 1.57083333 1.12181818 1.65554465 5.23010753 1.76705049]
 [2.81993958 1.57083333 1.12181818 1.65554465 5.23010753 1.76705049]]
memememe
[[1.30364372 0.55843653 1.27608347 0.78163654 0.813

/Users/meemansasood/Library/Python/3.7/lib/python/site-packages/pandas/core/indexing.py:691: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value, self.name)


INFO:tensorflow:Restoring parameters from ./Saved_Networks/MMSE_Attention_Concentration/MMSE_Attention_Concentration.ckpt
Model restored: ./Saved_Networks/MMSE_Attention_Concentration/MMSE_Attention_Concentration.ckpt
::::::DECODING:::::::::
::::::::::::VP_misslist/MMSE_Attention_Concentration_vpmiss.csv
memememe
[[ 1.]
 [ 5.]
 [ 5.]
 [ 5.]
 [ 5.]
 [ 5.]
 [ 5.]
 [ 4.]
 [ 5.]
 [ 5.]
 [nan]
 [ 5.]
 [ 5.]
 [nan]
 [nan]
 [nan]
 [ 5.]
 [nan]
 [ 5.]
 [nan]
 [nan]
 [nan]
 [ 0.]
 [nan]
 [ 5.]
 [nan]
 [ 5.]
 [nan]
 [nan]
 [ 4.]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [ 5.]
 [nan]
 [nan]
 [ 3.]
 [ 0.]
 [ 3.]
 [nan]
 [nan]
 [nan]
 [ 4.]
 [ 4.]
 [ 4.]
 [ 2.]
 [ 2.]
 [ 2.]
 [ 2.]
 [ 4.]
 [ 4.]
 [ 3.]
 [ 3.]
 [ 3.]
 [ 3.]
 [ 3.]
 [ 3.]
 [ 4.]
 [ 4.]
 [ 5.]
 [ 1.]
 [ 1.]
 [ 2.]
 [ 2.]
 [ 2.]
 [ 2.]
 [ 1.]
 [ 3.]
 [ 3.]
 [ 4.]
 [ 5.]
 [ 5.]
 [ 4.]
 [ 4.]
 [ 5.]
 [ 5.]
 [ 5.]
 [ 5.]
 [ 5.]
 [ 3.]
 [ 3.]
 [ 3.]
 [ 3.]
 [ 5.]
 [ 4.]
 [ 1.]
 [ 3.]
 [ 3.]
 [ 3.]
 [ 5.]
 [ 5.]

[*] Defining Cost function...
INFO:tensorflow:Restoring parameters from ./Saved_Networks/MMSE_Attention_Concentration/MMSE_Attention_Concentration.ckpt
Model restored: ./Saved_Networks/MMSE_Attention_Concentration/MMSE_Attention_Concentration.ckpt
::::::DECODING:::::::::
::::::::::::VP_misslist/MMSE_Attention_Concentration_vpmiss.csv
memememe
[[ 1.]
 [ 5.]
 [ 5.]
 [ 5.]
 [ 5.]
 [ 5.]
 [ 5.]
 [ 4.]
 [ 5.]
 [ 5.]
 [nan]
 [ 5.]
 [ 5.]
 [nan]
 [nan]
 [nan]
 [ 5.]
 [nan]
 [ 5.]
 [nan]
 [nan]
 [nan]
 [ 0.]
 [nan]
 [ 5.]
 [nan]
 [ 5.]
 [nan]
 [nan]
 [ 4.]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [ 5.]
 [nan]
 [nan]
 [ 3.]
 [ 0.]
 [ 3.]
 [nan]
 [nan]
 [nan]
 [ 4.]
 [ 4.]
 [ 4.]
 [ 2.]
 [ 2.]
 [ 2.]
 [ 2.]
 [ 4.]
 [ 4.]
 [ 3.]
 [ 3.]
 [ 3.]
 [ 3.]
 [ 3.]
 [ 3.]
 [ 4.]
 [ 4.]
 [ 5.]
 [ 1.]
 [ 1.]
 [ 2.]
 [ 2.]
 [ 2.]
 [ 2.]
 [ 1.]
 [ 3.]
 [ 3.]
 [ 4.]
 [ 5.]
 [ 5.]
 [ 4.]
 [ 4.]
 [ 5.]
 [ 5.]
 [ 5.]
 [ 5.]
 [ 5.]
 [ 3.]
 [ 3.]
 [ 3.]
 [ 3.]
 [ 5.]
 [ 4.]
 [ 1.]
 [ 3

[*] Defining Cost function...


/Users/meemansasood/Library/Python/3.7/lib/python/site-packages/pandas/core/indexing.py:691: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value, self.name)


INFO:tensorflow:Restoring parameters from ./Saved_Networks/MMSE_Language/MMSE_Language.ckpt
Model restored: ./Saved_Networks/MMSE_Language/MMSE_Language.ckpt
::::::DECODING:::::::::
::::::::::::VP_misslist/MMSE_Language_vpmiss.csv
memememe
[[ 6.]
 [ 8.]
 [ 8.]
 [ 8.]
 [ 8.]
 [ 8.]
 [ 8.]
 [ 7.]
 [ 8.]
 [ 8.]
 [nan]
 [ 8.]
 [ 8.]
 [nan]
 [nan]
 [nan]
 [ 8.]
 [nan]
 [ 8.]
 [nan]
 [nan]
 [nan]
 [ 7.]
 [nan]
 [ 8.]
 [nan]
 [ 8.]
 [nan]
 [nan]
 [ 7.]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [ 8.]
 [nan]
 [nan]
 [ 7.]
 [ 8.]
 [ 8.]
 [nan]
 [nan]
 [nan]
 [ 9.]
 [ 9.]
 [ 9.]
 [ 9.]
 [ 9.]
 [ 8.]
 [ 8.]
 [ 9.]
 [ 9.]
 [ 8.]
 [ 8.]
 [ 9.]
 [ 9.]
 [ 9.]
 [ 9.]
 [ 9.]
 [ 9.]
 [ 8.]
 [ 9.]
 [ 9.]
 [ 8.]
 [ 8.]
 [ 7.]
 [ 7.]
 [ 9.]
 [ 9.]
 [ 9.]
 [ 9.]
 [ 9.]
 [ 9.]
 [ 9.]
 [ 9.]
 [ 9.]
 [ 9.]
 [ 9.]
 [ 9.]
 [ 9.]
 [ 9.]
 [ 9.]
 [ 9.]
 [ 9.]
 [ 9.]
 [ 8.]
 [ 8.]
 [ 9.]
 [ 9.]
 [ 9.]
 [ 9.]
 [ 8.]
 [ 8.]
 [ 7.]
 [ 8.]
 [ 8.]
 [ 8.]
 [ 8.]
 [ 8.]
 [ 8.]
 [ 8.]
 [ 8.]
 [ 8

Model restored: ./Saved_Networks/MMSE_Language/MMSE_Language.ckpt
::::::DECODING:::::::::
::::::::::::VP_misslist/MMSE_Language_vpmiss.csv
memememe
[[ 6.]
 [ 8.]
 [ 8.]
 [ 8.]
 [ 8.]
 [ 8.]
 [ 8.]
 [ 7.]
 [ 8.]
 [ 8.]
 [nan]
 [ 8.]
 [ 8.]
 [nan]
 [nan]
 [nan]
 [ 8.]
 [nan]
 [ 8.]
 [nan]
 [nan]
 [nan]
 [ 7.]
 [nan]
 [ 8.]
 [nan]
 [ 8.]
 [nan]
 [nan]
 [ 7.]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [ 8.]
 [nan]
 [nan]
 [ 7.]
 [ 8.]
 [ 8.]
 [nan]
 [nan]
 [nan]
 [ 9.]
 [ 9.]
 [ 9.]
 [ 9.]
 [ 9.]
 [ 8.]
 [ 8.]
 [ 9.]
 [ 9.]
 [ 8.]
 [ 8.]
 [ 9.]
 [ 9.]
 [ 9.]
 [ 9.]
 [ 9.]
 [ 9.]
 [ 8.]
 [ 9.]
 [ 9.]
 [ 8.]
 [ 8.]
 [ 7.]
 [ 7.]
 [ 9.]
 [ 9.]
 [ 9.]
 [ 9.]
 [ 9.]
 [ 9.]
 [ 9.]
 [ 9.]
 [ 9.]
 [ 9.]
 [ 9.]
 [ 9.]
 [ 9.]
 [ 9.]
 [ 9.]
 [ 9.]
 [ 9.]
 [ 9.]
 [ 8.]
 [ 8.]
 [ 9.]
 [ 9.]
 [ 9.]
 [ 9.]
 [ 8.]
 [ 8.]
 [ 7.]
 [ 8.]
 [ 8.]
 [ 8.]
 [ 8.]
 [ 8.]
 [ 8.]
 [ 8.]
 [ 8.]
 [ 8.]
 [ 8.]
 [ 8.]
 [ 8.]
 [ 8.]
 [ 8.]
 [ 8.]
 [ 8.]
 [ 8.]
 [ 8.]
 [ 8.]
 [ 8.]
 [ 8.]
 [ 8.

/Users/meemansasood/Library/Python/3.7/lib/python/site-packages/pandas/core/indexing.py:691: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value, self.name)


INFO:tensorflow:Restoring parameters from ./Saved_Networks/MMSE_Memory_Recall/MMSE_Memory_Recall.ckpt
Model restored: ./Saved_Networks/MMSE_Memory_Recall/MMSE_Memory_Recall.ckpt
::::::DECODING:::::::::
::::::::::::VP_misslist/MMSE_Memory_Recall_vpmiss.csv
memememe
[[ 0.]
 [ 1.]
 [ 2.]
 [ 0.]
 [ 1.]
 [ 0.]
 [ 1.]
 [ 2.]
 [ 1.]
 [ 2.]
 [nan]
 [ 1.]
 [ 1.]
 [nan]
 [nan]
 [nan]
 [ 3.]
 [nan]
 [ 3.]
 [nan]
 [nan]
 [nan]
 [ 1.]
 [nan]
 [ 1.]
 [nan]
 [ 0.]
 [nan]
 [nan]
 [ 1.]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [ 2.]
 [nan]
 [nan]
 [ 0.]
 [ 2.]
 [ 0.]
 [nan]
 [nan]
 [nan]
 [ 2.]
 [ 2.]
 [ 2.]
 [ 2.]
 [ 2.]
 [ 2.]
 [ 3.]
 [ 0.]
 [ 2.]
 [ 1.]
 [ 1.]
 [ 2.]
 [ 2.]
 [ 1.]
 [ 1.]
 [ 3.]
 [ 3.]
 [ 3.]
 [ 1.]
 [ 1.]
 [ 0.]
 [ 0.]
 [ 1.]
 [ 1.]
 [ 0.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 0.]
 [ 0.]
 [ 1.]
 [ 1.]
 [ 0.]
 [ 0.]
 [ 2.]
 [ 2.]
 [ 1.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 1.]
 [ 0.]
 [ 1.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 1.]
 [ 1.]
 [ 3.]
 [ 2.]
 [ 2.]
 [ 3.]
 [ 0.]
 [ 3.]
 [ 3.]


[*] Defining Cost function...
INFO:tensorflow:Restoring parameters from ./Saved_Networks/MMSE_Memory_Recall/MMSE_Memory_Recall.ckpt
Model restored: ./Saved_Networks/MMSE_Memory_Recall/MMSE_Memory_Recall.ckpt
::::::DECODING:::::::::
::::::::::::VP_misslist/MMSE_Memory_Recall_vpmiss.csv
memememe
[[ 0.]
 [ 1.]
 [ 2.]
 [ 0.]
 [ 1.]
 [ 0.]
 [ 1.]
 [ 2.]
 [ 1.]
 [ 2.]
 [nan]
 [ 1.]
 [ 1.]
 [nan]
 [nan]
 [nan]
 [ 3.]
 [nan]
 [ 3.]
 [nan]
 [nan]
 [nan]
 [ 1.]
 [nan]
 [ 1.]
 [nan]
 [ 0.]
 [nan]
 [nan]
 [ 1.]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [ 2.]
 [nan]
 [nan]
 [ 0.]
 [ 2.]
 [ 0.]
 [nan]
 [nan]
 [nan]
 [ 2.]
 [ 2.]
 [ 2.]
 [ 2.]
 [ 2.]
 [ 2.]
 [ 3.]
 [ 0.]
 [ 2.]
 [ 1.]
 [ 1.]
 [ 2.]
 [ 2.]
 [ 1.]
 [ 1.]
 [ 3.]
 [ 3.]
 [ 3.]
 [ 1.]
 [ 1.]
 [ 0.]
 [ 0.]
 [ 1.]
 [ 1.]
 [ 0.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 0.]
 [ 0.]
 [ 1.]
 [ 1.]
 [ 0.]
 [ 0.]
 [ 2.]
 [ 2.]
 [ 1.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 1.]
 [ 0.]
 [ 1.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 1.]
 [ 1.]
 [ 3.]
 [ 2.]
 [ 2.

/Users/meemansasood/Library/Python/3.7/lib/python/site-packages/pandas/core/indexing.py:691: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value, self.name)


[*] Defining Cost function...
INFO:tensorflow:Restoring parameters from ./Saved_Networks/MMSE_Orientation/MMSE_Orientation.ckpt
Model restored: ./Saved_Networks/MMSE_Orientation/MMSE_Orientation.ckpt
::::::DECODING:::::::::
::::::::::::VP_misslist/MMSE_Orientation_vpmiss.csv
memememe
[[ 8.]
 [10.]
 [10.]
 [ 8.]
 [ 9.]
 [10.]
 [10.]
 [ 8.]
 [10.]
 [10.]
 [nan]
 [10.]
 [10.]
 [nan]
 [nan]
 [nan]
 [10.]
 [nan]
 [10.]
 [nan]
 [nan]
 [nan]
 [10.]
 [nan]
 [ 8.]
 [nan]
 [10.]
 [nan]
 [nan]
 [ 8.]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [ 9.]
 [nan]
 [nan]
 [ 7.]
 [ 6.]
 [ 8.]
 [nan]
 [nan]
 [nan]
 [10.]
 [10.]
 [10.]
 [10.]
 [10.]
 [ 9.]
 [ 9.]
 [ 9.]
 [ 7.]
 [ 9.]
 [ 9.]
 [ 7.]
 [ 9.]
 [10.]
 [10.]
 [10.]
 [10.]
 [10.]
 [10.]
 [10.]
 [ 8.]
 [ 8.]
 [10.]
 [10.]
 [ 7.]
 [10.]
 [10.]
 [ 9.]
 [10.]
 [10.]
 [ 9.]
 [ 9.]
 [ 9.]
 [ 9.]
 [10.]
 [10.]
 [10.]
 [ 8.]
 [ 9.]
 [ 9.]
 [ 8.]
 [ 8.]
 [ 9.]
 [ 9.]
 [ 8.]
 [ 9.]
 [ 9.]
 [ 9.]
 [10.]
 [10.]
 [10.]
 [ 8.]
 [10.]
 

[*] Defining Cost function...
INFO:tensorflow:Restoring parameters from ./Saved_Networks/MMSE_Orientation/MMSE_Orientation.ckpt
Model restored: ./Saved_Networks/MMSE_Orientation/MMSE_Orientation.ckpt
::::::DECODING:::::::::
::::::::::::VP_misslist/MMSE_Orientation_vpmiss.csv
memememe
[[ 8.]
 [10.]
 [10.]
 [ 8.]
 [ 9.]
 [10.]
 [10.]
 [ 8.]
 [10.]
 [10.]
 [nan]
 [10.]
 [10.]
 [nan]
 [nan]
 [nan]
 [10.]
 [nan]
 [10.]
 [nan]
 [nan]
 [nan]
 [10.]
 [nan]
 [ 8.]
 [nan]
 [10.]
 [nan]
 [nan]
 [ 8.]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [ 9.]
 [nan]
 [nan]
 [ 7.]
 [ 6.]
 [ 8.]
 [nan]
 [nan]
 [nan]
 [10.]
 [10.]
 [10.]
 [10.]
 [10.]
 [ 9.]
 [ 9.]
 [ 9.]
 [ 7.]
 [ 9.]
 [ 9.]
 [ 7.]
 [ 9.]
 [10.]
 [10.]
 [10.]
 [10.]
 [10.]
 [10.]
 [10.]
 [ 8.]
 [ 8.]
 [10.]
 [10.]
 [ 7.]
 [10.]
 [10.]
 [ 9.]
 [10.]
 [10.]
 [ 9.]
 [ 9.]
 [ 9.]
 [ 9.]
 [10.]
 [10.]
 [10.]
 [ 8.]
 [ 9.]
 [ 9.]
 [ 8.]
 [ 8.]
 [ 9.]
 [ 9.]
 [ 8.]
 [ 9.]
 [ 9.]
 [ 9.]
 [10.]
 [10.]
 [10.]
 [ 8.]
 [10.]
 

[*] Defining Cost function...


/Users/meemansasood/Library/Python/3.7/lib/python/site-packages/pandas/core/indexing.py:691: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value, self.name)


INFO:tensorflow:Restoring parameters from ./Saved_Networks/MMSE_Working_Memory_Registration/MMSE_Working_Memory_Registration.ckpt
Model restored: ./Saved_Networks/MMSE_Working_Memory_Registration/MMSE_Working_Memory_Registration.ckpt
::::::DECODING:::::::::
::::::::::::VP_misslist/MMSE_Working_Memory_Registration_vpmiss.csv
memememe
[[ 3.]
 [ 3.]
 [ 3.]
 [ 3.]
 [ 2.]
 [ 3.]
 [ 3.]
 [ 3.]
 [ 3.]
 [ 3.]
 [nan]
 [ 3.]
 [ 3.]
 [nan]
 [nan]
 [nan]
 [ 3.]
 [nan]
 [ 3.]
 [nan]
 [nan]
 [nan]
 [ 3.]
 [nan]
 [ 3.]
 [nan]
 [ 3.]
 [nan]
 [nan]
 [ 3.]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [ 3.]
 [nan]
 [nan]
 [ 3.]
 [ 2.]
 [ 3.]
 [nan]
 [nan]
 [nan]
 [ 3.]
 [ 3.]
 [ 3.]
 [ 3.]
 [ 3.]
 [ 3.]
 [ 3.]
 [ 3.]
 [ 2.]
 [ 3.]
 [ 3.]
 [ 3.]
 [ 3.]
 [ 3.]
 [ 3.]
 [ 3.]
 [ 3.]
 [ 3.]
 [ 3.]
 [ 3.]
 [ 3.]
 [ 3.]
 [ 3.]
 [ 3.]
 [ 3.]
 [ 3.]
 [ 3.]
 [ 3.]
 [ 3.]
 [ 3.]
 [ 3.]
 [ 3.]
 [ 3.]
 [ 3.]
 [ 3.]
 [ 3.]
 [ 3.]
 [ 3.]
 [ 3.]
 [ 3.]
 [ 3.]
 [ 3.]
 [ 3.]
 [ 3.]
 [ 3.]
 [ 3.]


[*] Defining Cost function...
INFO:tensorflow:Restoring parameters from ./Saved_Networks/MMSE_Working_Memory_Registration/MMSE_Working_Memory_Registration.ckpt
Model restored: ./Saved_Networks/MMSE_Working_Memory_Registration/MMSE_Working_Memory_Registration.ckpt
::::::DECODING:::::::::
::::::::::::VP_misslist/MMSE_Working_Memory_Registration_vpmiss.csv
memememe
[[ 3.]
 [ 3.]
 [ 3.]
 [ 3.]
 [ 2.]
 [ 3.]
 [ 3.]
 [ 3.]
 [ 3.]
 [ 3.]
 [nan]
 [ 3.]
 [ 3.]
 [nan]
 [nan]
 [nan]
 [ 3.]
 [nan]
 [ 3.]
 [nan]
 [nan]
 [nan]
 [ 3.]
 [nan]
 [ 3.]
 [nan]
 [ 3.]
 [nan]
 [nan]
 [ 3.]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [ 3.]
 [nan]
 [nan]
 [ 3.]
 [ 2.]
 [ 3.]
 [nan]
 [nan]
 [nan]
 [ 3.]
 [ 3.]
 [ 3.]
 [ 3.]
 [ 3.]
 [ 3.]
 [ 3.]
 [ 3.]
 [ 2.]
 [ 3.]
 [ 3.]
 [ 3.]
 [ 3.]
 [ 3.]
 [ 3.]
 [ 3.]
 [ 3.]
 [ 3.]
 [ 3.]
 [ 3.]
 [ 3.]
 [ 3.]
 [ 3.]
 [ 3.]
 [ 3.]
 [ 3.]
 [ 3.]
 [ 3.]
 [ 3.]
 [ 3.]
 [ 3.]
 [ 3.]
 [ 3.]
 [ 3.]
 [ 3.]
 [ 3.]
 [ 3.]
 [ 3.]
 [ 3.]
 [ 3.]
 [ 3.]
 [ 3.

/Users/meemansasood/Library/Python/3.7/lib/python/site-packages/pandas/core/indexing.py:691: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value, self.name)


[*] Defining Encoder...
[*] Defining Decoder...
[*] Defining Cost function...
INFO:tensorflow:Restoring parameters from ./Saved_Networks/MotorDrawingFeatures/MotorDrawingFeatures.ckpt
Model restored: ./Saved_Networks/MotorDrawingFeatures/MotorDrawingFeatures.ckpt
::::::DECODING:::::::::
::::::::::::VP_misslist/MotorDrawingFeatures_vpmiss.csv
memememe
[[2.62738454e-01 3.20645388e-02 5.87044534e-01 ... 7.50902435e+00
  5.98132634e+00 5.15361760e+00]
 [1.67298708e-01 1.27908810e-02 8.09128631e-01 ... 2.01443064e+00
  6.94031446e+00 5.09454277e+00]
 [2.78926802e-01 5.52097299e-02 5.81395349e-01 ... 4.01685475e+00
  9.83146326e+00 9.02842640e+00]
 ...
 [1.55769301e-01 8.91270445e-03 7.47967480e-01 ... 1.48404149e+00
  6.76364239e+00 3.91001569e+00]
 [1.55769301e-01 8.91270445e-03 7.47967480e-01 ... 1.48404149e+00
  6.76364239e+00 3.91001569e+00]
 [1.55769301e-01 8.91270445e-03 7.47967480e-01 ... 1.48404149e+00
  6.76364239e+00 3.91001569e+00]]
memememe
[[2.62738454e-01 3.20645388e-02 5.8704

[*] Importing model: model_HIVAE_inputDropout
[*] Defining placeholders
[*] Defining Encoder...
[*] Defining Decoder...
[*] Defining Cost function...
INFO:tensorflow:Restoring parameters from ./Saved_Networks/MotorDrawingFeatures/MotorDrawingFeatures.ckpt
Model restored: ./Saved_Networks/MotorDrawingFeatures/MotorDrawingFeatures.ckpt
::::::DECODING:::::::::
::::::::::::VP_misslist/MotorDrawingFeatures_vpmiss.csv
memememe
[[2.62738454e-01 3.20645388e-02 5.87044534e-01 ... 7.50902435e+00
  5.98132634e+00 5.15361760e+00]
 [1.67298708e-01 1.27908810e-02 8.09128631e-01 ... 2.01443064e+00
  6.94031446e+00 5.09454277e+00]
 [2.78926802e-01 5.52097299e-02 5.81395349e-01 ... 4.01685475e+00
  9.83146326e+00 9.02842640e+00]
 ...
 [1.55769301e-01 8.91270445e-03 7.47967480e-01 ... 1.48404149e+00
  6.76364239e+00 3.91001569e+00]
 [1.55769301e-01 8.91270445e-03 7.47967480e-01 ... 1.48404149e+00
  6.76364239e+00 3.91001569e+00]
 [1.55769301e-01 8.91270445e-03 7.47967480e-01 ... 1.48404149e+00
  6.76364

[*] Importing model: model_HIVAE_inputDropout
[*] Defining placeholders
[*] Defining Encoder...
[*] Defining Decoder...
[*] Defining Cost function...
INFO:tensorflow:Restoring parameters from ./Saved_Networks/MotorDrawingFeatures/MotorDrawingFeatures.ckpt
Model restored: ./Saved_Networks/MotorDrawingFeatures/MotorDrawingFeatures.ckpt
::::::DECODING:::::::::
::::::::::::VP_misslist/MotorDrawingFeatures_vpmiss.csv
memememe
[[2.62738454e-01 3.20645388e-02 5.87044534e-01 ... 7.50902435e+00
  5.98132634e+00 5.15361760e+00]
 [1.67298708e-01 1.27908810e-02 8.09128631e-01 ... 2.01443064e+00
  6.94031446e+00 5.09454277e+00]
 [2.78926802e-01 5.52097299e-02 5.81395349e-01 ... 4.01685475e+00
  9.83146326e+00 9.02842640e+00]
 ...
 [1.55769301e-01 8.91270445e-03 7.47967480e-01 ... 1.48404149e+00
  6.76364239e+00 3.91001569e+00]
 [1.55769301e-01 8.91270445e-03 7.47967480e-01 ... 1.48404149e+00
  6.76364239e+00 3.91001569e+00]
 [1.55769301e-01 8.91270445e-03 7.47967480e-01 ... 1.48404149e+00
  6.76364

[*] Importing model: model_HIVAE_inputDropout
[*] Defining placeholders
[*] Defining Encoder...
[*] Defining Decoder...
[*] Defining Cost function...
INFO:tensorflow:Restoring parameters from ./Saved_Networks/MotorDrawingFeatures/MotorDrawingFeatures.ckpt
Model restored: ./Saved_Networks/MotorDrawingFeatures/MotorDrawingFeatures.ckpt
::::::DECODING:::::::::
::::::::::::VP_misslist/MotorDrawingFeatures_vpmiss.csv
memememe
[[2.62738454e-01 3.20645388e-02 5.87044534e-01 ... 7.50902435e+00
  5.98132634e+00 5.15361760e+00]
 [1.67298708e-01 1.27908810e-02 8.09128631e-01 ... 2.01443064e+00
  6.94031446e+00 5.09454277e+00]
 [2.78926802e-01 5.52097299e-02 5.81395349e-01 ... 4.01685475e+00
  9.83146326e+00 9.02842640e+00]
 ...
 [1.55769301e-01 8.91270445e-03 7.47967480e-01 ... 1.48404149e+00
  6.76364239e+00 3.91001569e+00]
 [1.55769301e-01 8.91270445e-03 7.47967480e-01 ... 1.48404149e+00
  6.76364239e+00 3.91001569e+00]
 [1.55769301e-01 8.91270445e-03 7.47967480e-01 ... 1.48404149e+00
  6.76364

[*] Importing model: model_HIVAE_inputDropout
[*] Defining placeholders
[*] Defining Encoder...
[*] Defining Decoder...
[*] Defining Cost function...
INFO:tensorflow:Restoring parameters from ./Saved_Networks/MotorDrawingFeatures/MotorDrawingFeatures.ckpt
Model restored: ./Saved_Networks/MotorDrawingFeatures/MotorDrawingFeatures.ckpt
::::::DECODING:::::::::
::::::::::::VP_misslist/MotorDrawingFeatures_vpmiss.csv
memememe
[[2.62738454e-01 3.20645388e-02 5.87044534e-01 ... 7.50902435e+00
  5.98132634e+00 5.15361760e+00]
 [1.67298708e-01 1.27908810e-02 8.09128631e-01 ... 2.01443064e+00
  6.94031446e+00 5.09454277e+00]
 [2.78926802e-01 5.52097299e-02 5.81395349e-01 ... 4.01685475e+00
  9.83146326e+00 9.02842640e+00]
 ...
 [1.55769301e-01 8.91270445e-03 7.47967480e-01 ... 1.48404149e+00
  6.76364239e+00 3.91001569e+00]
 [1.55769301e-01 8.91270445e-03 7.47967480e-01 ... 1.48404149e+00
  6.76364239e+00 3.91001569e+00]
 [1.55769301e-01 8.91270445e-03 7.47967480e-01 ... 1.48404149e+00
  6.76364

[*] Importing model: model_HIVAE_inputDropout
[*] Defining placeholders
[*] Defining Encoder...
[*] Defining Decoder...
[*] Defining Cost function...
INFO:tensorflow:Restoring parameters from ./Saved_Networks/MotorDrawingFeatures/MotorDrawingFeatures.ckpt
Model restored: ./Saved_Networks/MotorDrawingFeatures/MotorDrawingFeatures.ckpt
::::::DECODING:::::::::
::::::::::::VP_misslist/MotorDrawingFeatures_vpmiss.csv
memememe
[[2.62738454e-01 3.20645388e-02 5.87044534e-01 ... 7.50902435e+00
  5.98132634e+00 5.15361760e+00]
 [1.67298708e-01 1.27908810e-02 8.09128631e-01 ... 2.01443064e+00
  6.94031446e+00 5.09454277e+00]
 [2.78926802e-01 5.52097299e-02 5.81395349e-01 ... 4.01685475e+00
  9.83146326e+00 9.02842640e+00]
 ...
 [1.55769301e-01 8.91270445e-03 7.47967480e-01 ... 1.48404149e+00
  6.76364239e+00 3.91001569e+00]
 [1.55769301e-01 8.91270445e-03 7.47967480e-01 ... 1.48404149e+00
  6.76364239e+00 3.91001569e+00]
 [1.55769301e-01 8.91270445e-03 7.47967480e-01 ... 1.48404149e+00
  6.76364

[*] Importing model: model_HIVAE_inputDropout
[*] Defining placeholders
[*] Defining Encoder...
[*] Defining Decoder...
[*] Defining Cost function...
INFO:tensorflow:Restoring parameters from ./Saved_Networks/MotorDrawingFeatures/MotorDrawingFeatures.ckpt
Model restored: ./Saved_Networks/MotorDrawingFeatures/MotorDrawingFeatures.ckpt
::::::DECODING:::::::::
::::::::::::VP_misslist/MotorDrawingFeatures_vpmiss.csv
memememe
[[2.62738454e-01 3.20645388e-02 5.87044534e-01 ... 7.50902435e+00
  5.98132634e+00 5.15361760e+00]
 [1.67298708e-01 1.27908810e-02 8.09128631e-01 ... 2.01443064e+00
  6.94031446e+00 5.09454277e+00]
 [2.78926802e-01 5.52097299e-02 5.81395349e-01 ... 4.01685475e+00
  9.83146326e+00 9.02842640e+00]
 ...
 [1.55769301e-01 8.91270445e-03 7.47967480e-01 ... 1.48404149e+00
  6.76364239e+00 3.91001569e+00]
 [1.55769301e-01 8.91270445e-03 7.47967480e-01 ... 1.48404149e+00
  6.76364239e+00 3.91001569e+00]
 [1.55769301e-01 8.91270445e-03 7.47967480e-01 ... 1.48404149e+00
  6.76364

[*] Importing model: model_HIVAE_inputDropout
[*] Defining placeholders
[*] Defining Encoder...
[*] Defining Decoder...
[*] Defining Cost function...
INFO:tensorflow:Restoring parameters from ./Saved_Networks/MotorDrawingFeatures/MotorDrawingFeatures.ckpt
Model restored: ./Saved_Networks/MotorDrawingFeatures/MotorDrawingFeatures.ckpt
::::::DECODING:::::::::
::::::::::::VP_misslist/MotorDrawingFeatures_vpmiss.csv
memememe
[[2.62738454e-01 3.20645388e-02 5.87044534e-01 ... 7.50902435e+00
  5.98132634e+00 5.15361760e+00]
 [1.67298708e-01 1.27908810e-02 8.09128631e-01 ... 2.01443064e+00
  6.94031446e+00 5.09454277e+00]
 [2.78926802e-01 5.52097299e-02 5.81395349e-01 ... 4.01685475e+00
  9.83146326e+00 9.02842640e+00]
 ...
 [1.55769301e-01 8.91270445e-03 7.47967480e-01 ... 1.48404149e+00
  6.76364239e+00 3.91001569e+00]
 [1.55769301e-01 8.91270445e-03 7.47967480e-01 ... 1.48404149e+00
  6.76364239e+00 3.91001569e+00]
 [1.55769301e-01 8.91270445e-03 7.47967480e-01 ... 1.48404149e+00
  6.76364

[*] Importing model: model_HIVAE_inputDropout
[*] Defining placeholders
[*] Defining Encoder...
[*] Defining Decoder...
[*] Defining Cost function...
INFO:tensorflow:Restoring parameters from ./Saved_Networks/MotorDrawingFeatures/MotorDrawingFeatures.ckpt
Model restored: ./Saved_Networks/MotorDrawingFeatures/MotorDrawingFeatures.ckpt
::::::DECODING:::::::::
::::::::::::VP_misslist/MotorDrawingFeatures_vpmiss.csv
memememe
[[2.62738454e-01 3.20645388e-02 5.87044534e-01 ... 7.50902435e+00
  5.98132634e+00 5.15361760e+00]
 [1.67298708e-01 1.27908810e-02 8.09128631e-01 ... 2.01443064e+00
  6.94031446e+00 5.09454277e+00]
 [2.78926802e-01 5.52097299e-02 5.81395349e-01 ... 4.01685475e+00
  9.83146326e+00 9.02842640e+00]
 ...
 [1.55769301e-01 8.91270445e-03 7.47967480e-01 ... 1.48404149e+00
  6.76364239e+00 3.91001569e+00]
 [1.55769301e-01 8.91270445e-03 7.47967480e-01 ... 1.48404149e+00
  6.76364239e+00 3.91001569e+00]
 [1.55769301e-01 8.91270445e-03 7.47967480e-01 ... 1.48404149e+00
  6.76364

[*] Importing model: model_HIVAE_inputDropout
[*] Defining placeholders
[*] Defining Encoder...
[*] Defining Decoder...
[*] Defining Cost function...
INFO:tensorflow:Restoring parameters from ./Saved_Networks/MotorDrawingFeatures/MotorDrawingFeatures.ckpt
Model restored: ./Saved_Networks/MotorDrawingFeatures/MotorDrawingFeatures.ckpt
::::::DECODING:::::::::
::::::::::::VP_misslist/MotorDrawingFeatures_vpmiss.csv
memememe
[[2.62738454e-01 3.20645388e-02 5.87044534e-01 ... 7.50902435e+00
  5.98132634e+00 5.15361760e+00]
 [1.67298708e-01 1.27908810e-02 8.09128631e-01 ... 2.01443064e+00
  6.94031446e+00 5.09454277e+00]
 [2.78926802e-01 5.52097299e-02 5.81395349e-01 ... 4.01685475e+00
  9.83146326e+00 9.02842640e+00]
 ...
 [1.55769301e-01 8.91270445e-03 7.47967480e-01 ... 1.48404149e+00
  6.76364239e+00 3.91001569e+00]
 [1.55769301e-01 8.91270445e-03 7.47967480e-01 ... 1.48404149e+00
  6.76364239e+00 3.91001569e+00]
 [1.55769301e-01 8.91270445e-03 7.47967480e-01 ... 1.48404149e+00
  6.76364

/Users/meemansasood/Library/Python/3.7/lib/python/site-packages/pandas/core/indexing.py:691: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value, self.name)


[*] Importing model: model_HIVAE_inputDropout
[*] Defining placeholders
[*] Defining Encoder...
[*] Defining Decoder...
[*] Defining Cost function...
INFO:tensorflow:Restoring parameters from ./Saved_Networks/MotorTappingFeatures/MotorTappingFeatures.ckpt
Model restored: ./Saved_Networks/MotorTappingFeatures/MotorTappingFeatures.ckpt
::::::DECODING:::::::::
::::::::::::VP_misslist/MotorTappingFeatures_vpmiss.csv
memememe
[[3.31196501e+00 2.64774912e+01 8.00000000e+00 ... 1.00000000e+02
  2.35050000e+00 6.72000000e-02]
 [1.99556095e-01 9.20596452e-03 1.90000000e+01 ... 1.06250000e+02
  1.00329412e+00 5.79411765e-02]
 [3.82692302e-01 3.67547437e-02 2.80000000e+01 ... 1.06250000e+02
  6.09529412e-01 4.36470588e-02]
 ...
 [1.98634269e-01 1.14508130e-02 1.50000000e+01 ... 1.06250000e+02
  6.26588235e-01 0.00000000e+00]
 [1.98634269e-01 1.14508130e-02 1.50000000e+01 ... 1.06250000e+02
  6.26588235e-01 0.00000000e+00]
 [1.98634269e-01 1.14508130e-02 1.50000000e+01 ... 1.06250000e+02
  6.26588

[*] Defining Encoder...
[*] Defining Decoder...
[*] Defining Cost function...
INFO:tensorflow:Restoring parameters from ./Saved_Networks/MotorTappingFeatures/MotorTappingFeatures.ckpt
Model restored: ./Saved_Networks/MotorTappingFeatures/MotorTappingFeatures.ckpt
::::::DECODING:::::::::
::::::::::::VP_misslist/MotorTappingFeatures_vpmiss.csv
memememe
[[3.31196501e+00 2.64774912e+01 8.00000000e+00 ... 1.00000000e+02
  2.35050000e+00 6.72000000e-02]
 [1.99556095e-01 9.20596452e-03 1.90000000e+01 ... 1.06250000e+02
  1.00329412e+00 5.79411765e-02]
 [3.82692302e-01 3.67547437e-02 2.80000000e+01 ... 1.06250000e+02
  6.09529412e-01 4.36470588e-02]
 ...
 [1.98634269e-01 1.14508130e-02 1.50000000e+01 ... 1.06250000e+02
  6.26588235e-01 0.00000000e+00]
 [1.98634269e-01 1.14508130e-02 1.50000000e+01 ... 1.06250000e+02
  6.26588235e-01 0.00000000e+00]
 [1.98634269e-01 1.14508130e-02 1.50000000e+01 ... 1.06250000e+02
  6.26588235e-01 0.00000000e+00]]
memememe
[[3.31196501e+00 2.64774912e+01 8.0000

[*] Defining Encoder...
[*] Defining Decoder...
[*] Defining Cost function...
INFO:tensorflow:Restoring parameters from ./Saved_Networks/MotorTappingFeatures/MotorTappingFeatures.ckpt
Model restored: ./Saved_Networks/MotorTappingFeatures/MotorTappingFeatures.ckpt
::::::DECODING:::::::::
::::::::::::VP_misslist/MotorTappingFeatures_vpmiss.csv
memememe
[[3.31196501e+00 2.64774912e+01 8.00000000e+00 ... 1.00000000e+02
  2.35050000e+00 6.72000000e-02]
 [1.99556095e-01 9.20596452e-03 1.90000000e+01 ... 1.06250000e+02
  1.00329412e+00 5.79411765e-02]
 [3.82692302e-01 3.67547437e-02 2.80000000e+01 ... 1.06250000e+02
  6.09529412e-01 4.36470588e-02]
 ...
 [1.98634269e-01 1.14508130e-02 1.50000000e+01 ... 1.06250000e+02
  6.26588235e-01 0.00000000e+00]
 [1.98634269e-01 1.14508130e-02 1.50000000e+01 ... 1.06250000e+02
  6.26588235e-01 0.00000000e+00]
 [1.98634269e-01 1.14508130e-02 1.50000000e+01 ... 1.06250000e+02
  6.26588235e-01 0.00000000e+00]]
memememe
[[3.31196501e+00 2.64774912e+01 8.0000

[*] Defining Encoder...
[*] Defining Decoder...
[*] Defining Cost function...
INFO:tensorflow:Restoring parameters from ./Saved_Networks/MotorTappingFeatures/MotorTappingFeatures.ckpt
Model restored: ./Saved_Networks/MotorTappingFeatures/MotorTappingFeatures.ckpt
::::::DECODING:::::::::
::::::::::::VP_misslist/MotorTappingFeatures_vpmiss.csv
memememe
[[3.31196501e+00 2.64774912e+01 8.00000000e+00 ... 1.00000000e+02
  2.35050000e+00 6.72000000e-02]
 [1.99556095e-01 9.20596452e-03 1.90000000e+01 ... 1.06250000e+02
  1.00329412e+00 5.79411765e-02]
 [3.82692302e-01 3.67547437e-02 2.80000000e+01 ... 1.06250000e+02
  6.09529412e-01 4.36470588e-02]
 ...
 [1.98634269e-01 1.14508130e-02 1.50000000e+01 ... 1.06250000e+02
  6.26588235e-01 0.00000000e+00]
 [1.98634269e-01 1.14508130e-02 1.50000000e+01 ... 1.06250000e+02
  6.26588235e-01 0.00000000e+00]
 [1.98634269e-01 1.14508130e-02 1.50000000e+01 ... 1.06250000e+02
  6.26588235e-01 0.00000000e+00]]
memememe
[[3.31196501e+00 2.64774912e+01 8.0000

[*] Defining Encoder...
[*] Defining Decoder...
[*] Defining Cost function...
INFO:tensorflow:Restoring parameters from ./Saved_Networks/MotorTappingFeatures/MotorTappingFeatures.ckpt
Model restored: ./Saved_Networks/MotorTappingFeatures/MotorTappingFeatures.ckpt
::::::DECODING:::::::::
::::::::::::VP_misslist/MotorTappingFeatures_vpmiss.csv
memememe
[[3.31196501e+00 2.64774912e+01 8.00000000e+00 ... 1.00000000e+02
  2.35050000e+00 6.72000000e-02]
 [1.99556095e-01 9.20596452e-03 1.90000000e+01 ... 1.06250000e+02
  1.00329412e+00 5.79411765e-02]
 [3.82692302e-01 3.67547437e-02 2.80000000e+01 ... 1.06250000e+02
  6.09529412e-01 4.36470588e-02]
 ...
 [1.98634269e-01 1.14508130e-02 1.50000000e+01 ... 1.06250000e+02
  6.26588235e-01 0.00000000e+00]
 [1.98634269e-01 1.14508130e-02 1.50000000e+01 ... 1.06250000e+02
  6.26588235e-01 0.00000000e+00]
 [1.98634269e-01 1.14508130e-02 1.50000000e+01 ... 1.06250000e+02
  6.26588235e-01 0.00000000e+00]]
memememe
[[3.31196501e+00 2.64774912e+01 8.0000

[*] Defining Encoder...
[*] Defining Decoder...
[*] Defining Cost function...
INFO:tensorflow:Restoring parameters from ./Saved_Networks/MotorTappingFeatures/MotorTappingFeatures.ckpt
Model restored: ./Saved_Networks/MotorTappingFeatures/MotorTappingFeatures.ckpt
::::::DECODING:::::::::
::::::::::::VP_misslist/MotorTappingFeatures_vpmiss.csv
memememe
[[3.31196501e+00 2.64774912e+01 8.00000000e+00 ... 1.00000000e+02
  2.35050000e+00 6.72000000e-02]
 [1.99556095e-01 9.20596452e-03 1.90000000e+01 ... 1.06250000e+02
  1.00329412e+00 5.79411765e-02]
 [3.82692302e-01 3.67547437e-02 2.80000000e+01 ... 1.06250000e+02
  6.09529412e-01 4.36470588e-02]
 ...
 [1.98634269e-01 1.14508130e-02 1.50000000e+01 ... 1.06250000e+02
  6.26588235e-01 0.00000000e+00]
 [1.98634269e-01 1.14508130e-02 1.50000000e+01 ... 1.06250000e+02
  6.26588235e-01 0.00000000e+00]
 [1.98634269e-01 1.14508130e-02 1.50000000e+01 ... 1.06250000e+02
  6.26588235e-01 0.00000000e+00]]
memememe
[[3.31196501e+00 2.64774912e+01 8.0000

[*] Defining Encoder...
[*] Defining Decoder...
[*] Defining Cost function...
INFO:tensorflow:Restoring parameters from ./Saved_Networks/MotorTappingFeatures/MotorTappingFeatures.ckpt
Model restored: ./Saved_Networks/MotorTappingFeatures/MotorTappingFeatures.ckpt
::::::DECODING:::::::::
::::::::::::VP_misslist/MotorTappingFeatures_vpmiss.csv
memememe
[[3.31196501e+00 2.64774912e+01 8.00000000e+00 ... 1.00000000e+02
  2.35050000e+00 6.72000000e-02]
 [1.99556095e-01 9.20596452e-03 1.90000000e+01 ... 1.06250000e+02
  1.00329412e+00 5.79411765e-02]
 [3.82692302e-01 3.67547437e-02 2.80000000e+01 ... 1.06250000e+02
  6.09529412e-01 4.36470588e-02]
 ...
 [1.98634269e-01 1.14508130e-02 1.50000000e+01 ... 1.06250000e+02
  6.26588235e-01 0.00000000e+00]
 [1.98634269e-01 1.14508130e-02 1.50000000e+01 ... 1.06250000e+02
  6.26588235e-01 0.00000000e+00]
 [1.98634269e-01 1.14508130e-02 1.50000000e+01 ... 1.06250000e+02
  6.26588235e-01 0.00000000e+00]]
memememe
[[3.31196501e+00 2.64774912e+01 8.0000

[*] Defining Encoder...
[*] Defining Decoder...
[*] Defining Cost function...
INFO:tensorflow:Restoring parameters from ./Saved_Networks/MotorTappingFeatures/MotorTappingFeatures.ckpt
Model restored: ./Saved_Networks/MotorTappingFeatures/MotorTappingFeatures.ckpt
::::::DECODING:::::::::
::::::::::::VP_misslist/MotorTappingFeatures_vpmiss.csv
memememe
[[3.31196501e+00 2.64774912e+01 8.00000000e+00 ... 1.00000000e+02
  2.35050000e+00 6.72000000e-02]
 [1.99556095e-01 9.20596452e-03 1.90000000e+01 ... 1.06250000e+02
  1.00329412e+00 5.79411765e-02]
 [3.82692302e-01 3.67547437e-02 2.80000000e+01 ... 1.06250000e+02
  6.09529412e-01 4.36470588e-02]
 ...
 [1.98634269e-01 1.14508130e-02 1.50000000e+01 ... 1.06250000e+02
  6.26588235e-01 0.00000000e+00]
 [1.98634269e-01 1.14508130e-02 1.50000000e+01 ... 1.06250000e+02
  6.26588235e-01 0.00000000e+00]
 [1.98634269e-01 1.14508130e-02 1.50000000e+01 ... 1.06250000e+02
  6.26588235e-01 0.00000000e+00]]
memememe
[[3.31196501e+00 2.64774912e+01 8.0000

[*] Defining Encoder...
[*] Defining Decoder...
[*] Defining Cost function...
INFO:tensorflow:Restoring parameters from ./Saved_Networks/MotorTappingFeatures/MotorTappingFeatures.ckpt
Model restored: ./Saved_Networks/MotorTappingFeatures/MotorTappingFeatures.ckpt
::::::DECODING:::::::::
::::::::::::VP_misslist/MotorTappingFeatures_vpmiss.csv
memememe
[[3.31196501e+00 2.64774912e+01 8.00000000e+00 ... 1.00000000e+02
  2.35050000e+00 6.72000000e-02]
 [1.99556095e-01 9.20596452e-03 1.90000000e+01 ... 1.06250000e+02
  1.00329412e+00 5.79411765e-02]
 [3.82692302e-01 3.67547437e-02 2.80000000e+01 ... 1.06250000e+02
  6.09529412e-01 4.36470588e-02]
 ...
 [1.98634269e-01 1.14508130e-02 1.50000000e+01 ... 1.06250000e+02
  6.26588235e-01 0.00000000e+00]
 [1.98634269e-01 1.14508130e-02 1.50000000e+01 ... 1.06250000e+02
  6.26588235e-01 0.00000000e+00]
 [1.98634269e-01 1.14508130e-02 1.50000000e+01 ... 1.06250000e+02
  6.26588235e-01 0.00000000e+00]]
memememe
[[3.31196501e+00 2.64774912e+01 8.0000

[*] Defining Encoder...
[*] Defining Decoder...
[*] Defining Cost function...
INFO:tensorflow:Restoring parameters from ./Saved_Networks/MotorTappingFeatures/MotorTappingFeatures.ckpt
Model restored: ./Saved_Networks/MotorTappingFeatures/MotorTappingFeatures.ckpt
::::::DECODING:::::::::
::::::::::::VP_misslist/MotorTappingFeatures_vpmiss.csv
memememe
[[3.31196501e+00 2.64774912e+01 8.00000000e+00 ... 1.00000000e+02
  2.35050000e+00 6.72000000e-02]
 [1.99556095e-01 9.20596452e-03 1.90000000e+01 ... 1.06250000e+02
  1.00329412e+00 5.79411765e-02]
 [3.82692302e-01 3.67547437e-02 2.80000000e+01 ... 1.06250000e+02
  6.09529412e-01 4.36470588e-02]
 ...
 [1.98634269e-01 1.14508130e-02 1.50000000e+01 ... 1.06250000e+02
  6.26588235e-01 0.00000000e+00]
 [1.98634269e-01 1.14508130e-02 1.50000000e+01 ... 1.06250000e+02
  6.26588235e-01 0.00000000e+00]
 [1.98634269e-01 1.14508130e-02 1.50000000e+01 ... 1.06250000e+02
  6.26588235e-01 0.00000000e+00]]
memememe
[[3.31196501e+00 2.64774912e+01 8.0000

/Users/meemansasood/Library/Python/3.7/lib/python/site-packages/pandas/core/indexing.py:691: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value, self.name)


[*] Defining Encoder...
[*] Defining Decoder...
[*] Defining Cost function...
INFO:tensorflow:Restoring parameters from ./Saved_Networks/MotorTestDurations/MotorTestDurations.ckpt
Model restored: ./Saved_Networks/MotorTestDurations/MotorTestDurations.ckpt
::::::DECODING:::::::::
::::::::::::VP_misslist/MotorTestDurations_vpmiss.csv
memememe
[[ 5.152  2.183  0.209 ...  7.851  3.585 13.03 ]
 [ 5.368  2.151  1.917 ...  9.91   2.206 19.312]
 [ 1.993  1.207  1.085 ...  9.327  2.605 13.017]
 ...
 [ 4.667  2.045  1.922 ...  9.533  2.154 12.816]
 [ 4.667  2.045  1.922 ...  9.533  2.154 12.816]
 [ 4.667  2.045  1.922 ...  9.533  2.154 12.816]]
memememe
[[ 5.152  2.183  0.209 ...  7.851  3.585 13.03 ]
 [ 5.368  2.151  1.917 ...  9.91   2.206 19.312]
 [ 1.993  1.207  1.085 ...  9.327  2.605 13.017]
 ...
 [ 4.667  2.045  1.922 ...  9.533  2.154 12.816]
 [ 4.667  2.045  1.922 ...  9.533  2.154 12.816]
 [ 4.667  2.045  1.922 ...  9.533  2.154 12.816]]
memememe
[[ 5.152  2.183  0.209 ...  7.851  3.58

[*] Defining Encoder...
[*] Defining Decoder...
[*] Defining Cost function...
INFO:tensorflow:Restoring parameters from ./Saved_Networks/MotorTestDurations/MotorTestDurations.ckpt
Model restored: ./Saved_Networks/MotorTestDurations/MotorTestDurations.ckpt
::::::DECODING:::::::::
::::::::::::VP_misslist/MotorTestDurations_vpmiss.csv
memememe
[[ 5.152  2.183  0.209 ...  7.851  3.585 13.03 ]
 [ 5.368  2.151  1.917 ...  9.91   2.206 19.312]
 [ 1.993  1.207  1.085 ...  9.327  2.605 13.017]
 ...
 [ 4.667  2.045  1.922 ...  9.533  2.154 12.816]
 [ 4.667  2.045  1.922 ...  9.533  2.154 12.816]
 [ 4.667  2.045  1.922 ...  9.533  2.154 12.816]]
memememe
[[ 5.152  2.183  0.209 ...  7.851  3.585 13.03 ]
 [ 5.368  2.151  1.917 ...  9.91   2.206 19.312]
 [ 1.993  1.207  1.085 ...  9.327  2.605 13.017]
 ...
 [ 4.667  2.045  1.922 ...  9.533  2.154 12.816]
 [ 4.667  2.045  1.922 ...  9.533  2.154 12.816]
 [ 4.667  2.045  1.922 ...  9.533  2.154 12.816]]
memememe
[[ 5.152  2.183  0.209 ...  7.851  3.58

[*] Defining Encoder...
[*] Defining Decoder...
[*] Defining Cost function...
INFO:tensorflow:Restoring parameters from ./Saved_Networks/MotorTestDurations/MotorTestDurations.ckpt
Model restored: ./Saved_Networks/MotorTestDurations/MotorTestDurations.ckpt
::::::DECODING:::::::::
::::::::::::VP_misslist/MotorTestDurations_vpmiss.csv
memememe
[[ 5.152  2.183  0.209 ...  7.851  3.585 13.03 ]
 [ 5.368  2.151  1.917 ...  9.91   2.206 19.312]
 [ 1.993  1.207  1.085 ...  9.327  2.605 13.017]
 ...
 [ 4.667  2.045  1.922 ...  9.533  2.154 12.816]
 [ 4.667  2.045  1.922 ...  9.533  2.154 12.816]
 [ 4.667  2.045  1.922 ...  9.533  2.154 12.816]]
memememe
[[ 5.152  2.183  0.209 ...  7.851  3.585 13.03 ]
 [ 5.368  2.151  1.917 ...  9.91   2.206 19.312]
 [ 1.993  1.207  1.085 ...  9.327  2.605 13.017]
 ...
 [ 4.667  2.045  1.922 ...  9.533  2.154 12.816]
 [ 4.667  2.045  1.922 ...  9.533  2.154 12.816]
 [ 4.667  2.045  1.922 ...  9.533  2.154 12.816]]
memememe
[[ 5.152  2.183  0.209 ...  7.851  3.58

[*] Defining Encoder...
[*] Defining Decoder...
[*] Defining Cost function...
INFO:tensorflow:Restoring parameters from ./Saved_Networks/MotorTestDurations/MotorTestDurations.ckpt
Model restored: ./Saved_Networks/MotorTestDurations/MotorTestDurations.ckpt
::::::DECODING:::::::::
::::::::::::VP_misslist/MotorTestDurations_vpmiss.csv
memememe
[[ 5.152  2.183  0.209 ...  7.851  3.585 13.03 ]
 [ 5.368  2.151  1.917 ...  9.91   2.206 19.312]
 [ 1.993  1.207  1.085 ...  9.327  2.605 13.017]
 ...
 [ 4.667  2.045  1.922 ...  9.533  2.154 12.816]
 [ 4.667  2.045  1.922 ...  9.533  2.154 12.816]
 [ 4.667  2.045  1.922 ...  9.533  2.154 12.816]]
memememe
[[ 5.152  2.183  0.209 ...  7.851  3.585 13.03 ]
 [ 5.368  2.151  1.917 ...  9.91   2.206 19.312]
 [ 1.993  1.207  1.085 ...  9.327  2.605 13.017]
 ...
 [ 4.667  2.045  1.922 ...  9.533  2.154 12.816]
 [ 4.667  2.045  1.922 ...  9.533  2.154 12.816]
 [ 4.667  2.045  1.922 ...  9.533  2.154 12.816]]
memememe
[[ 5.152  2.183  0.209 ...  7.851  3.58

[*] Defining Encoder...
[*] Defining Decoder...
[*] Defining Cost function...
INFO:tensorflow:Restoring parameters from ./Saved_Networks/MotorTestDurations/MotorTestDurations.ckpt
Model restored: ./Saved_Networks/MotorTestDurations/MotorTestDurations.ckpt
::::::DECODING:::::::::
::::::::::::VP_misslist/MotorTestDurations_vpmiss.csv
memememe
[[ 5.152  2.183  0.209 ...  7.851  3.585 13.03 ]
 [ 5.368  2.151  1.917 ...  9.91   2.206 19.312]
 [ 1.993  1.207  1.085 ...  9.327  2.605 13.017]
 ...
 [ 4.667  2.045  1.922 ...  9.533  2.154 12.816]
 [ 4.667  2.045  1.922 ...  9.533  2.154 12.816]
 [ 4.667  2.045  1.922 ...  9.533  2.154 12.816]]
memememe
[[ 5.152  2.183  0.209 ...  7.851  3.585 13.03 ]
 [ 5.368  2.151  1.917 ...  9.91   2.206 19.312]
 [ 1.993  1.207  1.085 ...  9.327  2.605 13.017]
 ...
 [ 4.667  2.045  1.922 ...  9.533  2.154 12.816]
 [ 4.667  2.045  1.922 ...  9.533  2.154 12.816]
 [ 4.667  2.045  1.922 ...  9.533  2.154 12.816]]
memememe
[[ 5.152  2.183  0.209 ...  7.851  3.58

[*] Defining Encoder...
[*] Defining Decoder...
[*] Defining Cost function...
INFO:tensorflow:Restoring parameters from ./Saved_Networks/MotorTestDurations/MotorTestDurations.ckpt
Model restored: ./Saved_Networks/MotorTestDurations/MotorTestDurations.ckpt
::::::DECODING:::::::::
::::::::::::VP_misslist/MotorTestDurations_vpmiss.csv
memememe
[[ 5.152  2.183  0.209 ...  7.851  3.585 13.03 ]
 [ 5.368  2.151  1.917 ...  9.91   2.206 19.312]
 [ 1.993  1.207  1.085 ...  9.327  2.605 13.017]
 ...
 [ 4.667  2.045  1.922 ...  9.533  2.154 12.816]
 [ 4.667  2.045  1.922 ...  9.533  2.154 12.816]
 [ 4.667  2.045  1.922 ...  9.533  2.154 12.816]]
memememe
[[ 5.152  2.183  0.209 ...  7.851  3.585 13.03 ]
 [ 5.368  2.151  1.917 ...  9.91   2.206 19.312]
 [ 1.993  1.207  1.085 ...  9.327  2.605 13.017]
 ...
 [ 4.667  2.045  1.922 ...  9.533  2.154 12.816]
 [ 4.667  2.045  1.922 ...  9.533  2.154 12.816]
 [ 4.667  2.045  1.922 ...  9.533  2.154 12.816]]
memememe
[[ 5.152  2.183  0.209 ...  7.851  3.58

[*] Defining Encoder...
[*] Defining Decoder...
[*] Defining Cost function...
INFO:tensorflow:Restoring parameters from ./Saved_Networks/MotorTestDurations/MotorTestDurations.ckpt
Model restored: ./Saved_Networks/MotorTestDurations/MotorTestDurations.ckpt
::::::DECODING:::::::::
::::::::::::VP_misslist/MotorTestDurations_vpmiss.csv
memememe
[[ 5.152  2.183  0.209 ...  7.851  3.585 13.03 ]
 [ 5.368  2.151  1.917 ...  9.91   2.206 19.312]
 [ 1.993  1.207  1.085 ...  9.327  2.605 13.017]
 ...
 [ 4.667  2.045  1.922 ...  9.533  2.154 12.816]
 [ 4.667  2.045  1.922 ...  9.533  2.154 12.816]
 [ 4.667  2.045  1.922 ...  9.533  2.154 12.816]]
memememe
[[ 5.152  2.183  0.209 ...  7.851  3.585 13.03 ]
 [ 5.368  2.151  1.917 ...  9.91   2.206 19.312]
 [ 1.993  1.207  1.085 ...  9.327  2.605 13.017]
 ...
 [ 4.667  2.045  1.922 ...  9.533  2.154 12.816]
 [ 4.667  2.045  1.922 ...  9.533  2.154 12.816]
 [ 4.667  2.045  1.922 ...  9.533  2.154 12.816]]
memememe
[[ 5.152  2.183  0.209 ...  7.851  3.58

[*] Defining Encoder...
[*] Defining Decoder...
[*] Defining Cost function...
INFO:tensorflow:Restoring parameters from ./Saved_Networks/MotorTestDurations/MotorTestDurations.ckpt
Model restored: ./Saved_Networks/MotorTestDurations/MotorTestDurations.ckpt
::::::DECODING:::::::::
::::::::::::VP_misslist/MotorTestDurations_vpmiss.csv
memememe
[[ 5.152  2.183  0.209 ...  7.851  3.585 13.03 ]
 [ 5.368  2.151  1.917 ...  9.91   2.206 19.312]
 [ 1.993  1.207  1.085 ...  9.327  2.605 13.017]
 ...
 [ 4.667  2.045  1.922 ...  9.533  2.154 12.816]
 [ 4.667  2.045  1.922 ...  9.533  2.154 12.816]
 [ 4.667  2.045  1.922 ...  9.533  2.154 12.816]]
memememe
[[ 5.152  2.183  0.209 ...  7.851  3.585 13.03 ]
 [ 5.368  2.151  1.917 ...  9.91   2.206 19.312]
 [ 1.993  1.207  1.085 ...  9.327  2.605 13.017]
 ...
 [ 4.667  2.045  1.922 ...  9.533  2.154 12.816]
 [ 4.667  2.045  1.922 ...  9.533  2.154 12.816]
 [ 4.667  2.045  1.922 ...  9.533  2.154 12.816]]
memememe
[[ 5.152  2.183  0.209 ...  7.851  3.58

[*] Defining Encoder...
[*] Defining Decoder...
[*] Defining Cost function...
INFO:tensorflow:Restoring parameters from ./Saved_Networks/MotorTestDurations/MotorTestDurations.ckpt
Model restored: ./Saved_Networks/MotorTestDurations/MotorTestDurations.ckpt
::::::DECODING:::::::::
::::::::::::VP_misslist/MotorTestDurations_vpmiss.csv
memememe
[[ 5.152  2.183  0.209 ...  7.851  3.585 13.03 ]
 [ 5.368  2.151  1.917 ...  9.91   2.206 19.312]
 [ 1.993  1.207  1.085 ...  9.327  2.605 13.017]
 ...
 [ 4.667  2.045  1.922 ...  9.533  2.154 12.816]
 [ 4.667  2.045  1.922 ...  9.533  2.154 12.816]
 [ 4.667  2.045  1.922 ...  9.533  2.154 12.816]]
memememe
[[ 5.152  2.183  0.209 ...  7.851  3.585 13.03 ]
 [ 5.368  2.151  1.917 ...  9.91   2.206 19.312]
 [ 1.993  1.207  1.085 ...  9.327  2.605 13.017]
 ...
 [ 4.667  2.045  1.922 ...  9.533  2.154 12.816]
 [ 4.667  2.045  1.922 ...  9.533  2.154 12.816]
 [ 4.667  2.045  1.922 ...  9.533  2.154 12.816]]
memememe
[[ 5.152  2.183  0.209 ...  7.851  3.58

[*] Defining Encoder...
[*] Defining Decoder...
[*] Defining Cost function...
INFO:tensorflow:Restoring parameters from ./Saved_Networks/MotorTestDurations/MotorTestDurations.ckpt
Model restored: ./Saved_Networks/MotorTestDurations/MotorTestDurations.ckpt
::::::DECODING:::::::::
::::::::::::VP_misslist/MotorTestDurations_vpmiss.csv
memememe
[[ 5.152  2.183  0.209 ...  7.851  3.585 13.03 ]
 [ 5.368  2.151  1.917 ...  9.91   2.206 19.312]
 [ 1.993  1.207  1.085 ...  9.327  2.605 13.017]
 ...
 [ 4.667  2.045  1.922 ...  9.533  2.154 12.816]
 [ 4.667  2.045  1.922 ...  9.533  2.154 12.816]
 [ 4.667  2.045  1.922 ...  9.533  2.154 12.816]]
memememe
[[ 5.152  2.183  0.209 ...  7.851  3.585 13.03 ]
 [ 5.368  2.151  1.917 ...  9.91   2.206 19.312]
 [ 1.993  1.207  1.085 ...  9.327  2.605 13.017]
 ...
 [ 4.667  2.045  1.922 ...  9.533  2.154 12.816]
 [ 4.667  2.045  1.922 ...  9.533  2.154 12.816]
 [ 4.667  2.045  1.922 ...  9.533  2.154 12.816]]
memememe
[[ 5.152  2.183  0.209 ...  7.851  3.58

Get Loglikelihoods for R plot!

In [10]:
VPcodes = pd.read_csv('/Users/meemansasood/Documents/Documents_IT/VAMBN_Version5_mmseEncoded_final/data/data_out/main_VirtualPPts_10.csv')
sample_size=178
n=sample_size
dfs=list()
for f in files:
    # replace placeholders in template
    opts=dict(best_hyper[best_hyper['files'].copy()==f])
    opts['nbatch'].iloc[0]=sample_size
    settings=set_settings(opts,nepochs=1,modload=True,save=False)
    
    #run
    zcodes=VPcodes['zcode_'+re.sub('.csv','',f)]
    scodes=VPcodes['scode_'+re.sub('.csv','',f)] if 'scode_'+re.sub('.csv','',f) in VPcodes.columns else np.zeros(zcodes.shape)
    logliks = pd.DataFrame()
    for i in range(int(len(VPcodes)/n)):   
        loglik=helpers.dec_network_loglik(settings,zcodes,scodes,VP=True)
        loglik=np.nanmean(np.array(loglik).T,axis=1)
        loglik = pd.DataFrame(loglik)
        #decs = np.concatenate((decs, dec), axis = 0)
        logliks = logliks.append(loglik)
        print(logliks)
    subj=pd.read_csv('python_names/'+re.sub('.csv','',f)+'_subj.csv')['x']
    dat=pd.DataFrame(logliks)
    dat.columns=[f]
    dat['SUBJID']=subj
    dfs.append(dat)

decoded=helpers.merge_dat(dfs)
decoded.to_csv('virtual_logliks_10.csv',index=False)

/Users/meemansasood/Library/Python/3.7/lib/python/site-packages/pandas/core/indexing.py:691: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value, self.name)


Namespace(batch_size=178, data_file='data_python/ARObjectFinding.csv', dim_latent_s=1, dim_latent_y=1, dim_latent_y_partition=None, dim_latent_z=1, display=1, epochs=1, learning_rate=0.001, miss_file='Missing_test.csv', miss_percentage_test=0.0, miss_percentage_train=0.0, model_name='model_HIVAE_inputDropout', perp=10, plot=1, restore=1, save=2, save_file='ARObjectFinding', true_miss_file='data_python/ARObjectFinding_missing.csv', types_file='data_python/ARObjectFinding_types.csv')
[*] Importing model: model_HIVAE_inputDropout
[*] Defining placeholders
[*] Defining Encoder...
[*] Defining Decoder...
[*] Defining Cost function...
INFO:tensorflow:Restoring parameters from ./Saved_Networks/ARObjectFinding/ARObjectFinding.ckpt
Model restored: ./Saved_Networks/ARObjectFinding/ARObjectFinding.ckpt
::::::DECODING:::::::::
::::::::::::VP_misslist/ARObjectFinding_vpmiss.csv


ValueError: Cannot feed value of shape (1780, 1) for Tensor 'Placeholder_31:0', which has shape '(178, 1)'